### ISSUE TITLE
Sort option parity

### ISSUE THREAD

**Issue by ValerioLyndon** [Xyphyn/photon#100]
**Is your feature request related to a problem? Please describe.**
I often use Top 12 Hours on Lemmy, however Photon does not include this sort option. In fact, it lacks several Top sort options that exist on regular Lemmy front-ends.

**Describe the solution you'd like**
Parity with the default Lemmy sort options, including:
- Top Twelve Hours
- Top Three Months
- Top Six Months
- Top Nine Months
- Top Year

**Additional context**
This is what my instance sort options look like compared to Photon:
![](https://i.imgur.com/z05ofU7.png) ![](https://i.imgur.com/TKJnTVT.png)

I didn't see an issue or discussion for this so hopefully I am not duplicating anything.

**Comment by Xyphyn** [comment]
Will add

**Comment by Xyphyn** [comment]
FYI "Top All Time" is the "Top" sort.

**Comment by Xyphyn** [comment]
The dropdown isn't meant to show every single option, just the ones that aren't visible. I can change that though.
