### ISSUE TITLE
The handling of postDraft from local session storage is buggy. 

### ISSUE THREAD

**Issue by asimons04** [Xyphyn/photon#104]
**Describe the bug**
While I can see the benefit of keeping drafts somewhere (Lemmy does not have this functionality natively and it's something people _have_ asked for), the way it is in Photon is causing more problems that it's solving.

Specifically, this is causing "misfires" where posts are sent to the wrong community and/or with the wrong or inappropriate URL/image/body from a prior draft.

**Specific Issues**
Issue 1:  I can't reproduce this consistently, but sometimes the community that pre-fills when you click Create -> Post is the one from the saved draft instead of the one you are in.  ~~Possibly related to observed behavior mentioned in #101~~ 

Issue 2:  An abandoned post for one community bleeds over by pre-filling new posts from that draft for any other community.

Issue 3: With all of the, IMO unnecessary, placeholder values in the form elements, it's difficult to distinguish whether things like the URL are set from an earlier/unrelated draft or just a placeholder in an empty field.

**To Reproduce** (if applicable)
Unfortunately, I cannot reproduce issue 1 consistently.  The rest can be reproduced as below:

1. Click into a community and then create-> post
2. Enter a title/url/image, and post body.  Don't submit.
3. Click back to front page (abandon the post you started)
4. Click on another community
5. Click "Create -> Post" 
6. The draft details are from the unrelated, abandoned post from earlier.  Also, sometimes the community doesn't change to the current one (again, that part, I'm unable to reproduce consistently).

**Potential Solutions**
1.  Make saving post drafts an explicit/opt-in action rather than done automatically (e.g. add a "save as draft" button that would then store it to local session storage).   
  a.  In line with the above, store drafts in local storage more granularly so that drafts are saved on a per-community basis.
  b. Don't load drafts automatically.  Also make that an explicit action with a "Restore Draft" button if a draft post is found in local storage for the community you're posting in.

2. Get rid of placeholder text to make fields populated from a draft more apparent.  Mentioned in feature request #107 

**Versions**
- Browser: Firefox, Chromium
- Photon version: 0.8.4

**Comment by asimons04** [comment]
Doing a custom build and nuking all of the draft logic in `src/lib/components/lemmy/post/PostForm.svelte` is my current workaround.

**Comment by Xyphyn** [comment]
I decided to add a manual "restore from draft" button.
