### ISSUE TITLE
Refreshing the profile page of the logged-in user breaks the page

### ISSUE THREAD

**Issue by asimons04** [Xyphyn/photon#105]
**Describe the bug**
When accessing the page at /profile/user for your account, it loads correctly.  If you refresh the page, only an empty set of braces appears.  The /profile/user page will not work correctly again until you leave it completely and return.

**To Reproduce** (if applicable)
1.  Click the menu button and then "Profile".  You will see your posts/comments as expected.
2.  Refresh the page.
3. Observe `{}` under the User tab with no posts/comments.
4.  Click menu button again and select Profile.
5. Observe the User tab still remains empty with only `{}` until you leave /profile/user completely (e.g. back to frontpage) and return to your profile.

Note:  The "Settings" and "Blocks" tabs still work correctly, but the posts/comments that would normally appear under the "User" tab are broken on page refresh until you fully navigate away from /profile/user.

**Expected behavior**
Refreshing the /profile/user page should refresh the content.

**Screenshots**
![image](https://github.com/Xyphyn/photon/assets/69986579/7383b31c-98cd-4189-acce-a8d3de8ec1c2)

**Versions**
- Browser: Firefox
- Photon version: 0.8.4

**Comment by asimons04** [comment]
Seems to be the same issue as #98

If confirmed as such, this can be marked and closed as a duplicate.

**Comment by Xyphyn** [comment]
Yes, this is the same issue as #98
