### ISSUE TITLE
Settings page does not load

### ISSUE THREAD

**Issue by TailyFair** [Xyphyn/photon#111]
**Describe the bug**
Settings page does not load properly and just shows empty state.

**To Reproduce** (if applicable)
1. Go to `Settings` (no matter if logged in or not)
4. Wait for page to load and nothing else happens

**Expected behavior**
Settings page contents should load.

**Screenshots**
![image](https://github.com/Xyphyn/photon/assets/27275873/c633579b-5dd3-463e-a8b1-0ecb5447dbfd)

**Versions**
- Browser: Firefox and Edge
- Photon version: 0.9.6

**Comment by Xyphyn** [comment]
Fixed
