### ISSUE TITLE
Upload image gives "string doesn't match expected pattern"

### ISSUE THREAD

**Issue by jspayne** [Xyphyn/photon#112]
**Describe the bug**
When creating a post by uploading an image, I get the error "string doesn't match expected format"

**To Reproduce** (if applicable)
1. Go to Create, New Post
2. Click on image button
3. Click on Attach an Image, select file
4. Click upload

**Expected behavior**
Image uploads and is attached to the post

**Versions**
- Browser: Safari
- Photon version: 0.8.1 (according to package.json.  I can't find it anywhere else)

**Comment by Xyphyn** [comment]
Photon is at 0.9.6. Try updating to that first.

**Comment by jgeorgeson** [comment]
I'm seeing similar issues attaching images, either as the post URL, in the post body, or in a comment. For me it's returning a red 500 error response popup in the bottom-right. This is on photon.lemmy.world, running v0.9.6

**Comment by Xyphyn** [comment]
500 is a server side error, so it's probably an issue with lemmy.world. I'll make the error messages more helpful soon though.

**Comment by jgeorgeson** [comment]
I forgot to mention that I don't get the error when I switch back to plain old lemmy.world, only with photon.lemmy.world. Though it could still be a configuration issue with their deployment. I'll look for a replace to report it to the admins their too.

**Comment by Xyphyn** [comment]
This is due to how photon uploads images. Lemmy still has an issue where you can't upload images without a jwt, so i proxy it. It could be an issue with a rate limit or something

**Comment by Xyphyn** [comment]
Does this issue occur on Voyager as well? If so, it's for the same reason

**Comment by jgeorgeson** [comment]
I am able to upload images posting at m.lemmy.world.

**Comment by Xyphyn** [comment]
Strange. It's a 500, so it seems to be a server error. This will be fixed once Lemmy fixes CORS.
