### ISSUE TITLE
HREF Spilling over to surrounding text

### ISSUE THREAD

**Issue by RuthlessRuler** [Xyphyn/photon#117]
**Describe the bug**
When there is a text that has surrounding href/links, the text becomes parts of the HREF tag.

**To Reproduce** (if applicable)
1. Go to this comment: https://lemdro.id/comment/1370886
2. Check the same comment under Photon: https://p.lemdro.id/post/lemdro.id/757553?thread=0.1370886#1370886
3. See error

**Expected behavior**
The Link is not spilled over to text.

**Versions**
- Browser: Brave
- Photon version: 0.9.19

**Comment by Xyphyn** [comment]
Fixed in v0.9.20
