### ISSUE TITLE
Public photon instances

### ISSUE THREAD

**Issue by extremelyonline** [Xyphyn/photon#119]
**Describe alternatives you've considered**
Hi, cool app! Not sure if you're planning to add a list of public/community photon instances in this repo. Here's mine in case anyone is interested. Thanks!

[ph.opnxng.com](https://ph.opnxng.com/)
Hosted in Singapore
[Contact/privacy](https://about.opnxng.com/)

**Comment by Xyphyn** [comment]
Will add soon

**Comment by Xyphyn** [comment]
@extremelyonline This instance has `PUBLIC_INSTANCE_URL` set, meaning people who don't use lemm.ee can't login to anything else.

I added an environment variable in v0.9.27: `PUBLIC_LOCK_TO_INSTANCE` to set `PUBLIC_INSTANCE_URL` but to not lock it.
