### ISSUE TITLE
Pixeladed images in main feed

### ISSUE THREAD

**Issue by KAMiKAZOW** [Xyphyn/photon#121]
![image](https://github.com/Xyphyn/photon/assets/3259076/30a8a895-e01a-4e15-b634-5b723ce0d977)

**Comment by KAMiKAZOW** [comment]
Looks fine the post has been opened:

![image](https://github.com/Xyphyn/photon/assets/3259076/b9df494f-81f7-46b5-9408-4b5d2dddf388)

**Comment by Xyphyn** [comment]
This is due to how thumbnails work, not easy to fix without wasting a loooot of bandwidth

**Comment by KAMiKAZOW** [comment]
> This is due to how thumbnails work, not easy to fix without wasting a loooot of bandwidth

Don't you see from the screenshots that you needlessly increase the size of a much smaller image? Just display it in its native resolution.

**Comment by Xyphyn** [comment]
I guess I could change it to use max widths and height instead of explicitly setting it

**Comment by jared-teets** [comment]
This combined with image expansion on click from https://github.com/Xyphyn/photon/issues/128 would be an upgrade.

**Comment by Xyphyn** [comment]
I made it so that you can expand images on click for full res.
