### ISSUE TITLE
A way for theclient to change the instance url

### ISSUE THREAD

**Issue by extremelyonline** [Xyphyn/photon#123]
**Describe the solution you'd like**
Users can change the lemmy instance by clicking the instance url (e.g. lemmy.ml) at the top right.

**Describe alternatives you've considered**
Always appending the instance url (e.g. https://phtn.app/lemmy.ml), so that users can change it themselves.

**Comment by Xyphyn** [comment]
Login to your preferred instance or go to accounts > guest instance.
