### ISSUE TITLE
[Feature request] Copy link to the post on the original instance

### ISSUE THREAD

**Issue by forenta** [Xyphyn/photon#129]
**Is your feature request related to a problem? Please describe.**
Often I'd like to share a comment to my followers on Soapbox, Pleroma or Mastodon. On Lemmys UI, there's a *link* to the original source with the Fediverse-icon. That's at least a solution to right-click-copy-link and paste it at the other place.

**Describe the solution you'd like**
An icon that copies the link to the original post (not on my instance) to the clipboard.

**Describe alternatives you've considered**
At least a *link* to the post like on the Lemmy UI.

**Additional context**
I prefer vegan cookies.

**Comment by poVoq** [comment]
This seems to still have issues. If a non logged in user clicks on the three button menu on the post, they get an "Actions Copy Link" popup, but when clicking the "Copy Link" button the Firefox brower internal share menu opens, which has various options to share a link, but no option to copy the link to the clip-board.
