### ISSUE TITLE
Linear bulletin board layout

### ISSUE THREAD

**Issue by erlend-sh** [Xyphyn/photon#131]
Forum software with linear (aka non-nested) threads like Discourse, NodeBB and Flarum are all working on ActivityPub support. It’ll be easier for Lemmy to be compatible with these new entrants to the fediverse if it supports their linearized mode of conversation.

There’s already prior art for this in [LemmyBB](https://github.com/LemmyNet/lemmyBB), although it’s based on the very old-fashioned phpBB design.

To enforce this style for certain community-subs it’d require backend changes in Lemmy core. However, it can already be implemented as a completely optional view that users can toggle on-off on any thread they’re viewing. All that’s required are some trailing lines to show the depth in a linear way. These are two pictures of the same thread (ignore the one hidden comment in the Photon screenshot).

![IMG_2026](https://github.com/Xyphyn/photon/assets/583842/fb7a3697-b33a-437e-9b99-e52ec9087f1f)
![IMG_2079](https://github.com/Xyphyn/photon/assets/583842/16beeb3c-10b8-45af-91e9-fed1a5122b5c)

**Comment by Xyphyn** [comment]
BTW what browser are you using? I need to remove that arrow that's showing.

**Comment by Xyphyn** [comment]
Accidentally closed. Whoops

**Comment by Xyphyn** [comment]
Will consider this

**Comment by erlend-sh** [comment]
> BTW what browser are you using?
iOS Safari.

**Comment by Xyphyn** [comment]
may revisit in the future when i change the way post views are handled
