### ISSUE TITLE
Videos do not embed

### ISSUE THREAD

**Issue by CTalvio** [Xyphyn/photon#132]
**Describe the bug**
Videos do not embed

Go here: https://photon.lemmy.world/post/lemmy.world/4036907
And compare to: https://lemmy.world/post/4036907

**Expected behavior**
Videos should embed and be playable within Photon.

- Browser: Firefox
- Photon version: 1.0.7

**Comment by Xyphyn** [comment]
Currently it does not support m4v, will add
