### ISSUE TITLE
Option to move thumbnails on list view to the left

### ISSUE THREAD

**Issue by ShittyKopper** [Xyphyn/photon#145]
**Is your feature request related to a problem? Please describe.**
On any screen wider than an old laptop, there is way too much separation between the title/metadata of a post and the associated thumbnail (if there is any).

**Describe the solution you'd like**
An option to move the images to the left side of a post.

**Describe alternatives you've considered**
N/A

**Additional context**
The top post is how it looks now, the bottom post is how an option like this might look like, simulated with a quick CSS hack (flex-direction: row-reverse)

![image](https://github.com/Xyphyn/photon/assets/106974765/01ea07ea-e18b-4cb1-baf8-0828f86c81f1)

It'd be trivial to write a userstyle for this but there doesn't seem to be any meaningful classes/attributes I can attach CSS selectors to

**Comment by Xyphyn** [comment]
Is Photon using Atkinson Hyperlegible for some reason or is that your system font?

**Comment by ShittyKopper** [comment]
Oh yeah that's my system font. I have a really weird font setup and go to some ridiculous lengths to enforce it so you probably shouldn't worry about that.

**Comment by Xyphyn** [comment]
Actually Photon uses your system UI font by default. There is an option to use your browser font instead. Was just wondering because I was experimenting with how that font would look in Photon earlier and thought I may have accidentally pushed it everywhere 😂

**Comment by Xyphyn** [comment]
Will consider adding. Should be as simple as a flex-row-reverss
