### ISSUE TITLE
[Feature Request] Auto translate support

### ISSUE THREAD

**Issue by poVoq** [Xyphyn/photon#146]
**Is your feature request related to a problem? Please describe.**

One of the really nice new features of Mastodon and Akkoma is the option to auto-translate posts from a simple button in the context menu of a post.

**Describe the solution you'd like**
These link up to external APIs like Google Translate or deepl.com, but the nicest is actually to self-host LibreTranslate: https://libretranslate.com/

**Additional context**
I have a running LT for my Akkoma instance and if you need extended API access for testing it, please let me know.

**Comment by Xyphyn** [comment]
I like Photon having as little outside dependencies as possible, but I'll see what i can do in this aspect

**Comment by poVoq** [comment]
I just tried the new feature in 1.30.1 with my LibreTranslate instance, but I get a `Error: Input data should be a String` in the browser console.

Also it is not entirely clear that you need to leave out the `https://` in the settings.

Also, but inrelated, how can I set an default LT instance as an admin via ENV parameters?

**Comment by Xyphyn** [comment]
That means the translation failed

**Comment by poVoq** [comment]
Hmm, odd. Can you try with my LT instance? It should allow public access up to 5000 characters:

https://translate.f-hub.org

**Comment by Xyphyn** [comment]
Hmm I'll look into it

**Comment by Xyphyn** [comment]
i show an error message now
