### ISSUE TITLE
Powered by Photon misaligned in 1.9.2

### ISSUE THREAD

**Issue by poVoq** [Xyphyn/photon#148]
![grafik](https://github.com/Xyphyn/photon/assets/940360/c5bab734-69b1-4716-80e1-56ab591c5474)

On latest Firefox.

And maybe a small feature request: would it be possible to turn this "advertisement" off?

I don't mind there being a Photon link in the menu or at the bottom somewhere, but right below the main logo is a bit too much IMHO. Also easy to mis-click the link as the main logo is often used to reload the page and or return to the front page. Thanks!

**Comment by Xyphyn** [comment]
Added an ENV var and a setting to disable it as requested.

Also fixed the misalignment.
