### ISSUE TITLE
Add an Option to not mark a post as read / disable prefetch on hover

### ISSUE THREAD

**Issue by hanubeki** [Xyphyn/photon#157]
_Originally posted by @Xyphyn in https://github.com/Xyphyn/photon/issues/54#issuecomment-1733796191_

> > @Xyphyn
> > > If you hover over a post title it automatically marks as read
> > 
> > I don't really like this behaviour, I'm tired of using it because of this.
> 
> This is because it prefetches the post. I can add an option to not mark posts as read or to disable prefetching.

**Comment by hanubeki** [comment]
Please, add an option to that, this makes your app usable to me.

**Comment by Xyphyn** [comment]
Will add by the end of the day in pst

**Comment by Xyphyn** [comment]
Added an option to mark posts as read
