### ISSUE TITLE
Show instance/domain in sidebar

### ISSUE THREAD

**Issue by lorefnon** [Xyphyn/photon#161]
Hello, Thanks for creating this frontend - it looks really sleek and modern. 

**Is your feature request related to a problem? Please describe.**

When I am subscribed to multiple communities with same name (in separate instances), it is hard to distinguish between them from sidebar.

![image](https://github.com/Xyphyn/photon/assets/1449492/2d849670-e039-4a75-8e1d-1475c8fb7637)

**Describe the solution you'd like**

It would be good to have the instance (eg `typescript (@lemmy.ml)`) also as part of the label in the sidebar

**Comment by Xyphyn** [comment]
Will add soon. Currently working on v0.19.0 support

**Comment by Xyphyn** [comment]
Fixed in v1.16.0

**Comment by lorefnon** [comment]
Thank you 👍🏾 This is great.
