### ISSUE TITLE
[Bug Report]: Upvotes don't update counter of nested comments

### ISSUE THREAD

**Issue by TheSaneWriter** [Xyphyn/photon#166]
**Describe the bug**
Oftentimes, there are portions of the comment section with an "X More" button that will display additional replies. The comments displayed by this button will not have their points counter updated when you click upvote but will have their counters decremented when you click the upvote button again.

**To Reproduce** (if applicable)
1. Go to a post on a Photon instance, for example https://photon.thesanewriter.com/post/lemmy.thesanewriter.com/288790.
2. Scroll to a comment with a see more button.
3. Click the button.
4. Attempt to upvote the comment.

**Expected behavior**
The upvote is applied and the counter is incremented. Then, if I click it again, it will be decremented from the incremented number.

**Screenshots**
https://github.com/Xyphyn/photon/assets/93878758/8ff9e155-2e3a-4edd-9d07-8041c70d75df

**Versions**
- Browser: Firefox 118.0.2 (64-bit for Linux)
- Photon version: 1.18.2

**Comment by Xyphyn** [comment]
I've noticed this issue for a while. I have absolutely no clue what is causing it

**Comment by Xyphyn** [comment]
I plan to rewrite the Comment vote component anyway, don't worry about it
