### ISSUE TITLE
Reject registration applicationwith reason

### ISSUE THREAD

**Issue by Tmpod** [Xyphyn/photon#173]
**Is your feature request related to a problem? Please describe.**
As an instance admin, I'd like to be able to attach a reason to application denials.

**Describe the solution you'd like**
When reviewing an application, there could be a text input to attach a reason to the verdict.

**Describe alternatives you've considered**
Instead of a permanently visible text input, you could have one that pops up only when you click the red X button for denying.

**Additional context**
The official Lemmy UI implements the alternative suggestion above.

**Comment by Neshura87** [comment]
Second this, as of right now the Application Tab is useless in environments with more than one Admin or environments where Transparency is important. Given that the App is written in Svelte I may take a look later to see if I can Add the feature myself via a PR.

**Comment by Neshura87** [comment]
Created a PR for the Issue: #203

**Comment by Neshura87** [comment]
Can be closed, implemented with #203
