### ISSUE TITLE
Login expires on browser restart

### ISSUE THREAD

**Issue by Tealk** [Xyphyn/photon#184]
**Describe the bug**
When I restart the browser, I am logged out of my instance.
All the settings you have made will also be lost.

**To Reproduce** (if applicable)
1. Visit https://photon.rollenspiel.forum
2. click on login and enter your credentials
3. restart the browser

**Expected behavior**
I would have expected a more persistent cookie to be set to maintain the login.

**Versions**
- Browser: Firefox 119.0.1
- Photon version: v1.20.3

**Comment by Xyphyn** [comment]
This happens if you have site data to be deleted on exit (Firefox for some reason clears all site data if you clear history on exit), and this is the default behavior on librewolf. Check if this happens on other sites.

**Comment by Tealk** [comment]
but i don't delete the site data at all.

**Comment by Xyphyn** [comment]
"Offline website data" is localStorage, which Photon relies on.

**Comment by Tealk** [comment]
I wasn't expecting that. Thank you.

**Comment by Xyphyn** [comment]
No problem!
