### ISSUE TITLE
Profile information centered and looks horrible (0.18.5)

### ISSUE THREAD

**Issue by Fons-vitae-caritas** [Xyphyn/photon#186]
**Describe the bug**
The profile information is displayed centered when everything else is adjusted to the left. This looks very strange. 
Example can be seen here, this is my Lemmy.world profile: https://photon.lemmy.world/profile/user

**To Reproduce** (if applicable)
1. Go to a user profile
2. ??????
3. Profit. 

**Expected behavior**
The content should be adjusted to the left and fit properly. Golden line dose apply here..

**Screenshots**
![image](https://github.com/Xyphyn/photon/assets/150508220/5380204f-f743-4922-9a9a-2b6bba29042a)

**Versions**
- Browser: Chrome 
- Photon version: 0.18.5

**Comment by Xyphyn** [comment]
It's now centered to the left.
