### ISSUE TITLE
Settings option to open a new tab when clicking links.

### ISSUE THREAD

**Issue by Fons-vitae-caritas** [Xyphyn/photon#187]
When you click on links in photon you are going to that link directly in the same window/tab. It would be nice if there was an option in the settings page to let you open links in a new tab. 

I really like this theme but this is something that should be implemented as it's annoying as heck. 
Thanks!

**Comment by Xyphyn** [comment]
While this is being implemented, you can middle click links (click the scroll wheel) to open in a new tab.

**Comment by Fons-vitae-caritas** [comment]
> While this is being implemented, you can middle click links (click the scroll wheel) to open in a new tab.

Thanks! I'll keep that in mind.
