### ISSUE TITLE
Community links: Don't leave

### ISSUE THREAD

**Issue by sevonj** [Xyphyn/photon#188]
**Is your feature request related to a problem? Please describe.** 
Community links in found in sidebars take me away from Photon client.
Example link: `[!suomi@sopuli.xyz](https://sopuli.xyz/c/suomi) `
Result: `https://sopuli.xyz/c/suomi`

**Describe the solution you'd like**
Same behavior as official lemmy-ui: autotranslate the url to local.
Expected result: `photon_base_url/c/suomi@sopuli.xyz`

**Describe alternatives you've considered**
None.

**Additional context**
For example, check the sidebar at https://sopuli.xyz/c/suomi
![image](https://github.com/Xyphyn/photon/assets/100710152/0fdbc6b5-d027-4fc2-a4de-688446d64bf1)

**Comment by Xyphyn** [comment]
This must be an issue with how they made their link.

Instead of using `!` syntax and keeping it like that, they turned it into a link, probably like this:

```
[!mina_irl@sopuli.xyz](https://sopuli.xyz/c/mina_irl)
```

This is bad markdown on behalf of the user who wrote it.

**Comment by sevonj** [comment]
Do you mean these shouldn't be written as links at all?

I also think that is how it should be, but links are pretty common as Lemmy-UI autofills it like that for the user:

![image](https://github.com/Xyphyn/photon/assets/100710152/9b794b92-5ef4-469c-82ce-57739ece6ae2)
(click the green box)
![image](https://github.com/Xyphyn/photon/assets/100710152/33db1092-3532-4b33-8063-7754b333b9a5)

**Comment by Xyphyn** [comment]
Should be fixed in v1.24.0

**Comment by sevonj** [comment]
@Xyphyn I know I'm late, but I don't think this was ever resolved. 

Community identifiers converted into links by lemmy-ui still take me out of photon. I see these in community sidebars and [!newcommunities@lemmy.world](https://phtn.app/c/newcommunities@lemmy.world) a lot.
