### ISSUE TITLE
Collapse cross posts into the same post in the post feed

### ISSUE THREAD

**Issue by Ategon** [Xyphyn/photon#189]
**Is your feature request related to a problem? Please describe.**
Behaviour in lemmy-ui is to collapse posts with the same url into the same post in the post feed (showing the duplicates in a cross-posted to section). Photon doesn't follow that standard and instead shows all of the posts separatedly which can flood the feed if the same thing is being crossposted to multiple spots

**Describe the solution you'd like**
Adding in a cross-posted to section below the post in the post feed and move duplicate posts out of the posts that you are currently showing the user there. In lemmy-ui the oldest one is the one that still shows 

**Describe alternatives you've considered**
Removing cross-posts from showing up instead of having a section for them is another option although people might want to see the post in another community

**Additional context**
![282623308-96ec1c43-1a9e-4a0d-af7b-0636c7585c98](https://github.com/Xyphyn/photon/assets/73616169/3c3b2df3-2ab9-4f78-9190-297d839c5550)
![image](https://github.com/Xyphyn/photon/assets/73616169/93930d1d-d2a1-4898-b17a-502e8b5f5ad1)

**Comment by Xyphyn** [comment]
I planned to add this but didn't know how as lemmy doesn't provide a crossposts property in lists. I forgot that a crosspost is just posts with the same URL, thanks for letting me know! Adding soon

**Comment by Xyphyn** [comment]
Added in v1.21
