### ISSUE TITLE
Federation links not clickable

### ISSUE THREAD

**Issue by CorvetteCole** [Xyphyn/photon#19]
Example: ![image](https://github.com/Xyphyn/photon/assets/19213965/a7b925d2-44cf-4927-94a1-1f72dcc92752)

(you can see this in action at https://nu.lemdro.id)

**Comment by CorvetteCole** [comment]
This also applies to the sidebars for specific communities

**Comment by CorvetteCole** [comment]
Alright, I'm stupid. They just aren't clickable in general. Would be great to have support for this eventually!

**Comment by Xyphyn** [comment]
I'll add this once I figure out how to make custom markdown components with markdown-it
