### ISSUE TITLE
NS_BINDING_ABORTED with Firefox

### ISSUE THREAD

**Issue by pimeys** [Xyphyn/photon#190]
**Describe the bug**

When loading the frontpage with the latest version (1.21.2), quite often some of the images do not load and we see `NS_BINDING_ABORTED` errors in the console. These are way more common with the latest version compared to 1.20.x.

**To Reproduce** (if applicable)

1. Go to any Photon view, e.g. the frontpage with Firefox
2. Monitor the network tab
3. Some of the images take a long time to load, and the requests error with `NS_BINDING_ABORTED`

**Expected behavior**

The images should load fast and without problems.

**Screenshots**

![2023-11-15_16-11-1700062877](https://github.com/Xyphyn/photon/assets/34967/45d682df-387c-4632-ab5e-0fb843fbc229)

**Versions**
- Browser: Firefox 119.0
- Photon version: 1.21.2

**Comment by Xyphyn** [comment]
That's most likely an issue with their image host. Try going to the image url, it likely won't work.

**Comment by pimeys** [comment]
Yeah, it might be. I was thinking about that too, but when investigating I read that firefox tends to have this issue when rendering/requesting certain things in a certain order. And it hasn't been an issue before that much.

Might also be my network setup...
