### ISSUE TITLE
Missing posts

### ISSUE THREAD

**Issue by Tealk** [Xyphyn/photon#191]
**Describe the bug**
Not all posts that exist are displayed:
https://rollenspiel.forum/c/suche
https://photon.rollenspiel.forum/c/suche@rollenspiel.forum

**Expected behavior**
The same posts should be displayed on the Lemmy UI and the Photon UI.

**Screenshots**
![image](https://github.com/Xyphyn/photon/assets/12276250/299a62cb-15fc-4cbf-87e8-59313f097181)

![image](https://github.com/Xyphyn/photon/assets/12276250/02cde740-f33c-4102-a939-5bad7c21996f)

**Versions**
- Browser: Firefox 119.0.1
- Photon version: v1.21.1

**Comment by Xyphyn** [comment]
Could it be that the language being set is causing issues? Try making a post with "language" as "undetermined"

**Comment by Tealk** [comment]
undetermined is not enabled, I force the users to set a language

**Comment by Xyphyn** [comment]
I figured out the issue. Posts without a URL are missing, I didn't realize this and the bug would probably be here longer without this report.

A hot fix was added in docker image v1.21.3 until I can properly re-add crosspost combining.
