### ISSUE TITLE
Feature request: show users what instances or communities they're banned from

### ISSUE THREAD

**Issue by 0xCmdrKeen** [Xyphyn/photon#195]
**Is your feature request related to a problem? Please describe.**
I'm pretty new to Lemmy but I've already been banned from a few communities and one server, and I've noticed that this seems to happen rather silently. Only once did a moderator take the time to inform me about this, the other times I only found out because my comments or posts weren't getting any votes or responses, and then confirming my suspicion via the modlog.

We can argue about whether I was trolling or not, but due to the federated nature of Lemmy and the natural propensity of people with similar opinions to clump together, it is almost inevitable that any opinion whatsoever is going to offend someone, somewhere, and may result in a ban at some point. Things that may be acceptable on one server will be considered a no-no on another, and that's fine. This is after all by design, not by accident.

**Describe the solution you'd like**
What I'm proposing is a feature that would show people which instances or communities they're banned from, so they don't waste time or resources repeatedly posting there after having been banned. Since a user's posts are hosted on their home server, posting to such communities is still possible after all, since mods and admins can only ban you from their server. Meanwhile, if someone continues to do so without knowing that no one there will be able to see their posts, they are wasting resources on their home server by taking up storage space unnecessarily. 

Basically, what I'd like to see when visiting such a community or instance would be a small badge that says "you are banned from posting here", so I don't waste my time talking to people that aren't interested in my thoughts or opinions.

**Describe alternatives you've considered**
The alternative to this, as I've previously mentioned, appears to be manually visiting the modlog of a particular instance and searching for your username there to see if you are affected by any bans at the moment. This is awkward and time consuming. One can also make sure to unsubscribe from such communities, but that won't prevent them from showing up in the "All" feed, unless you block them as well, but that would just lead to users increasingly isolating themselves, and thus encourage more and more insularity over time.

**Comment by Xyphyn** [comment]
I don't think the Lemmy API provides a way to see this, so I'd recommend sending this to lemmy itself.

**Comment by 0xCmdrKeen** [comment]
@Xyphyn okay, I wasn't sure about this since I haven't looked into the API itself. I thought maybe it's possible to parse the modlog and show the results in a more convenient way?

**Comment by 0xCmdrKeen** [comment]
Okay, I did some experiments with the API and it seems to be feasible. If I implemented this myself and sent you a pull request, would you accept it?

**Comment by Xyphyn** [comment]
It depends on the implementation of it. I'd prefer if it didn't search the modlog, as it's one of the slowest parts of the lemmy API.

**Comment by Xyphyn** [comment]
> @Xyphyn okay, I wasn't sure about this since I haven't looked into the API itself. I thought maybe it's possible to parse the modlog and show the results in a more convenient way?
> 
> EDIT: just looked at the API docs and this might help? https://join-lemmy.org/api/interfaces/ModBanFromCommunityView.html

This is a response from the ban user call.

**Comment by 0xCmdrKeen** [comment]
> It depends on the implementation of it. I'd prefer if it didn't search the modlog, as it's one of the slowest parts of the lemmy API.

Fair enough. I'll see what I can do. 

> This is a response from the ban user call.

Yes, my bad. Sorry, I'm new to the API and the docs are confusing to say the least.

**Comment by 0xCmdrKeen** [comment]
Okay, how about this idea: instead of the modlog feature only showing the home instance, add another dropdown that allows to select another instance (but defaults to the home server). The autocomplete popup could be populated using `getFederatedInstances()` since there is no point to ever look at the modlog for an instance that doesn't federate with your home server anyways.

I've noticed that the modlog can show vastly different things depending on what server you're on, sometimes actions taken on other instances seem to show up, sometimes they don't. So only showing the modlog of the home instance seems to give an inaccurate view.
