### ISSUE TITLE
Feature request: Add setting to control default feed type and sort type

### ISSUE THREAD

**Issue by mbestavros** [Xyphyn/photon#2]
As is, Photon defaults to the `Local` feed type with `Active` sorting when navigating to the homepage.

Personally, I almost always use the `Subscribed` feed type. It would be nice if I could set that as the default.

As a workaround, I've bookmarked the URL with my preferred feed parameters:

```
https://photon.xylight.dev/?type=Subscribed&sort=Active
```

However, these parameters get erased when clicking on the app logo, so it's not a full solution.

**Comment by Xyphyn** [comment]
Good idea, I'll implement it inside user settings and then just get that in the +page.ts

**Comment by Xyphyn** [comment]
Added
