### ISSUE TITLE
Add support for instance taglines

### ISSUE THREAD

**Issue by CorvetteCole** [Xyphyn/photon#20]
I'll try not to make too many issues for you, but it would be great to display the instance tagline like the official UI does. I'm using it to present small snippets of information such as:
![image](https://github.com/Xyphyn/photon/assets/19213965/8da0864b-dc8f-4db7-a839-929cbad1559f)

It cycles through the taglines I've setup: 
![image](https://github.com/Xyphyn/photon/assets/19213965/d5da3641-5484-44ea-8a30-615c535fddb2)

I assume there is an API for these, but definitely not a priority!

**Comment by CorvetteCole** [comment]
I'm not sure how this would work, given that none of the other popular web apps do it and your application is built with the assumption that it is an independent application rather than attached to an instance. Feel free to close this as not planned if you feel it is not worth thinking about

**Comment by Xyphyn** [comment]
I can make it show based on GetSite, or if PUBLIC_INSTANCE_URL is set.
