### ISSUE TITLE
Feature request: add an option to open links in new tabs

### ISSUE THREAD

**Issue by 0xCmdrKeen** [Xyphyn/photon#200]
Currently, there is an option to open posts in new tabs by default (which confusingly is internally named `openLinksInNewTabs`). 

What I'd like to see is an option that *actually* opens links (at least those found in posts) in a new tab, NOT the post itself.

I suppose this could be a little tricky because of the aforementioned issue — since settings are stored in the user's `localStorage`, changing `openLinksInNewTabs` to actually open links in new tabs and using a setting named `openPostsInNewTabs` to store the preferences for the current behavior would mess with everyone's configuration when it's released. But I also can't think of a better name for the new setting that wouldn't lead to confusion on the development side.

Either way, it would be cool to have a setting like this in addition to the current one.

**Comment by Xyphyn** [comment]
I think this should be always on, so that's what i did.

**Comment by 0xCmdrKeen** [comment]
Works for me!
