### ISSUE TITLE
modlog search 404

### ISSUE THREAD

**Issue by Tealk** [Xyphyn/photon#201]
**Describe the bug**
It is not possible to select lemmy instances and then a 404 is displayed.

**To Reproduce** (if applicable)
1. open Lemmy photon
2. open the ModLog
3. enter a domain of a non-lemmy instance in the instance search

**Expected behavior**
a message that no modlog is available for the instance because it is not a lemmy instance.

**Screenshots**
![image](https://github.com/Xyphyn/photon/assets/12276250/26c07458-e69f-41a2-80dd-36196b170f92)
https://photon.rollenspiel.forum/modlog?instance=rollenspiel.social

**Versions**
- Browser: Firefox 120.0 
- Photon version:v1.23.2
  - check in the bottom of the main menu.

**Comment by 0xCmdrKeen** [comment]
Good catch. I recently contributed that feature. Will provide a fix.

**Comment by Xyphyn** [comment]
should be fixed
