### ISSUE TITLE
WEBM videos embedded in comments do not render correctly

### ISSUE THREAD

**Issue by 0xCmdrKeen** [Xyphyn/photon#205]
When a comment contains an embedded WEBM video, it is rendered by Photon using an `<img>` tag, which results in a simple horizontal bar for some reason.

This is likely caused by Lemmy using the same Markdown syntax as for images, i.e. `![](https://link_to/video.webm)`. This likely also affects other HTML5 video formats supported by that tag, such as MP4.

1. View a comment containing a WEBM video link in Lemmy (for example https://lemmy.world/comment/5652494)
2. The video appears correctly
3. View the same comment in Photon (https://phtn.app/post/lemmy.world/8813563?thread=0.5652494)
4. The video appears as a horizontal bar instead and is rendered using an `<img>` tag.

**Expected behavior**
The video should be rendered using a HTML5 `<video>` tag.

**Versions**
- Browser: Brave 1.60.118
- Photon version: 1.32.2

**Potential solution**
I did some research and it appears that the [markdown-it-html5-media](https://www.npmjs.com/package/markdown-it-html5-media) package solves this exact problem. Can send a pull request if desired.

**Comment by Xyphyn** [comment]
Didn't know there was a markdown plugin for this. Thanks!

**Comment by 0xCmdrKeen** [comment]
@Xyphyn you're welcome. Took me a while to find as there as 33 pages of markdown-it plugins listed on npmjs.com. 😅

**Comment by Xyphyn** [comment]
It seems this uses commonjs, which isn't supported by anything in javascript made after 1852. Unfortunately I can't use this

**Comment by 0xCmdrKeen** [comment]
Weird, I tried it myself and it worked fine on my machine...

**Comment by Xyphyn** [comment]
fixed
