### ISSUE TITLE
Profile picture in account switcher is not updated unless you delete the account and log in again

### ISSUE THREAD

**Issue by 0xCmdrKeen** [Xyphyn/photon#209]
**Describe the bug**
The profile picture in the account switcher isn't updated when you change it in your profile settings. The avatar on the top right of the page is, but the account switcher continues to show a generic avatar icon.

**To Reproduce** (if applicable)
1. Create an account
2. Log in on Photon
3. Open profile → Settings
4. Upload new profile image
5. Reload and observe the behavior described above

**Expected behavior**
The avatar in the account switcher should show the new profile picture

**Versions**
- Browser: Brave 1.60.125
- Photon version: 1.23.2

**Comment by Xyphyn** [comment]
should be better now
