### ISSUE TITLE
YouTube share links do not embed

### ISSUE THREAD

**Issue by CTalvio** [Xyphyn/photon#213]
**Describe the bug**
I noticed youtube videos are able to embed now and can be viewed without leaving the lemmy tab. This is nice, but it only works with youtube.com links and not share links in the youtu.be format.

**To Reproduce** (if applicable)
1. Go to a post where a yt video has been posted using a share link.

**Expected behavior**
Share links should embed same as the full url.

**Versions**
- Browser: Firefox
- Photon version: 1.23.2

**Comment by Xyphyn** [comment]
This is what happens when you make AI write regex lol

**Comment by CTalvio** [comment]
I noticed share links now embed, though they do not actually work.

![image](https://github.com/Xyphyn/photon/assets/4365015/a0049331-32a0-4ae2-ab55-4f6a284c5794)

**Comment by Xyphyn** [comment]
i think its fixed
