### ISSUE TITLE
Inbox "Jump" to comment link doesn't work / is not reliable

### ISSUE THREAD

**Issue by 0xCmdrKeen** [Xyphyn/photon#215]
**Describe the bug**
The inbox link on comment replies to jump to the original comment for context does not always seem to work. 

I'm not exactly sure under which circumstances it fails, but it does seem to become less reliable the deeper the comment chain goes. 

When it fails, it just shows the post page itself and one has to find the comment by scrolling manually. The data to identify the comment is still in the URL, but the browser does not jump there automatically for some reason.

**Expected behavior**
The link should work correctly every time. Alternatively, perhaps there could be a "show context" link that only shows the direct parent comment.

**Versions**
- Browser: Brave 1.60.125
- Photon version: 1.24.0

**Comment by Xyphyn** [comment]
This is because there's a max depth. I'll make it so that if the depth is greater than ~5, it'll add a "show context" button.

**Comment by 0xCmdrKeen** [comment]
Ah, that makes sense. It does indeed always seem to be the really long threads where it stops working.
