### ISSUE TITLE
Selecting community doesn't work in the search page

### ISSUE THREAD

**Issue by YousufSSyed** [Xyphyn/photon#216]
**To Reproduce** (if applicable)
1. Go to the seach page: 
2. Click on the down arrow.
3. Type in a community in the search bar and select one

**Expected behavior**
This happens sometimes not always but when I put down a community the box goes blank again.

**Versions**
- Browser: Firefox 12.0.1
- Photon version: 1.24.0
  - check in the bottom of the main menu.

**Comment by 0xCmdrKeen** [comment]
It DOES seem to work, as in, when you enter a search term and then pick a community, you will only see results from that community. But the community input not showing the community that's selected probably isn't ideal.

Also, when the community filter is active, the input should probably not disappear again.
