### ISSUE TITLE
Change URL scheme for posts to easily cut them to their original actual links.

### ISSUE THREAD

**Issue by YousufSSyed** [Xyphyn/photon#217]
URLS in Photon look like https://phtn.app/post/lemmy.dbzer0.com/9818364, I want to be able to cut out the past part and open it in a new tab to see if without the Photon UI. lemmy.dbzer0.com/9818364 is not valid but lemmy.dbzer0.com/post/9818364 is.

**Comment by Xyphyn** [comment]
For this you can use the "share" button. It takes the link from the instance itself

**Comment by YousufSSyed** [comment]
Oh that was really quick, I didn't even get to close the tab yet! 

I still think it would be nice, since I have to go to the dropdown menu and click share.

**Comment by Xyphyn** [comment]
The issue is, if you switched accounts and then reloaded the page without the instance specifier, it would bring up an error or a completely different post. This was done to prevent instance conflicts

**Comment by YousufSSyed** [comment]
Can u be more specific and or give examples? I don't know u what u mean.

**Comment by Xyphyn** [comment]
If you went to a post with just `/post/123`, Photon doesn't know which instance that post ID is for. (Each instance has its own post ids for posts) So it would just use the instance of your account. If you shared a Photon link to someone else, or switched accounts and reloaded the page, it would fetch that post ID on another instance, meaning you'll either get an error or a completely different post.

**Comment by YousufSSyed** [comment]
I see
