### ISSUE TITLE
Content not visible/linked in posts.

### ISSUE THREAD

**Issue by mihnt81** [Xyphyn/photon#222]
**Describe the bug**
When I visit posts that contain a gif file, no preview is shown and the link isn't there when viewing from the comments page. Seems to be it's not pulling/displaying the data.
I also had it happen on a video post this morning but I forget which site it was. Sorry, should have wrote it down/bookmarked it.

**To Reproduce** (if applicable)
1. Go to https://photon.lemmy.world/post/lemmy.world/9421515

**Expected behavior**
For an image preview to be there on the main page and for the content to be there when I click into the post.

**Screenshots**
![Screenshot from 2023-12-12 18-20-59](https://github.com/Xyphyn/photon/assets/36163746/d0d4c7c3-33ec-4a94-a449-af8a16193985)

**Versions**
- Browser: Flatpak Firefox 120.0.1
- Photon version: 1.23.2
  - check in the bottom of the main menu.

**Comment by Xyphyn** [comment]
Sorry for this bug- I found the issue and I'm fixing it right now.

**Comment by mihnt81** [comment]
> Sorry for this bug- I found the issue and I'm fixing it right now.

All good. Thanks for the better frontend!
