### ISSUE TITLE
Add a button to posts in the feed to expand the post body to show the full post

### ISSUE THREAD

**Issue by Tywele** [Xyphyn/photon#224]
**Is your feature request related to a problem? Please describe.**
Sometimes I don't want to read the comments to a post or I decide to read the comments after having read the post fully but don't want another page to load before deciding to do so but right now most of the posts in my feed are cut off by a fade effect.

**Describe the solution you'd like**
It would be nice to have a button or link at bottom of the post body in the feed that reads like "Show full post" or "more"/"show more" to expand the post body in the feed to show the full post. 

**Describe alternatives you've considered**
Alternatively there could be an option in the settings to show the full post body all the time in the feed

**Additional context**
![A screenshot showing a post as an example where the post body is cut off by the fade](https://github.com/Xyphyn/photon/assets/8156875/6d4596ad-f6bc-49d7-98c6-1b77d29bbd5a)

**Comment by Xyphyn** [comment]
Recently added in a commit, should appear in v1.24.2

**Comment by Tywele** [comment]
I think this functionality could be improved. If the post body is under a certain height the fade effect shouldn't be shown and the expand button is unnecessary. They (fade effect and expand button) should only start showing after the post body exceeds a certain height.
