### ISSUE TITLE
Showing post title when external link is attached in Cards, Cozy, List view

### ISSUE THREAD

**Issue by BrikoX** [Xyphyn/photon#226]
**Is your feature request related to a problem? Please describe.**
When the link is attached, the post title is not shown but the title from the link embed is shown instead and clicking on it leads to the external link not the post. It is a redundant functionality as it already has a hyperlink to the external link above the title.

**Describe the solution you'd like**
A setting to optionally show post title in all view modes no matter if the external link is attached or not. 

**Additional context**
![image 1](https://github.com/Xyphyn/photon/assets/69597682/2f4fa0ad-7a17-4c2a-88f4-276aaa3fdb09)
![image 2](https://github.com/Xyphyn/photon/assets/103123951/5d95013f-179e-4cf3-b9e7-3f69e62ce1c5)

**Comment by Xyphyn** [comment]
The top link is meant to be a visual indicator of which domain it links to. I can just make it so that the regular title is always visible I guess

**Comment by Xyphyn** [comment]
Regular title is now always visible
