### ISSUE TITLE
Display name setting doesn't work

### ISSUE THREAD

**Issue by BrikoX** [Xyphyn/photon#227]
**Describe the bug**
No matter which option is toggled display name is always shown. 

**To Reproduce** (if applicable)
1. Go to Settings > Use display name
2. Change the setting to on/off
3. See no change.

**Expected behavior**
When setting is off, the account name should be shown instead of display name. 

**Versions**
- Browser: All
- Photon version: v1.24.1

**Comment by 0xCmdrKeen** [comment]
There is an option to use the display name?

**Comment by madeofstown** [comment]
> There is an option to use the display name?

![Screenshot_20231227-083423](https://github.com/Xyphyn/photon/assets/33820964/54f36ecd-97cd-4ba2-a749-3765e4734fcd)

**Comment by 0xCmdrKeen** [comment]
@madeofstown Oh, right. Sorry, I confused this with another app.

**Comment by madeofstown** [comment]
Also doesn't seem to work when you set the environment variable `PUBLIC_DISPLAY_NAMES=false`

**Comment by Xyphyn** [comment]
I accidentally removed this feature a while ago when cleaning up some code it seems, will add back soon

**Comment by 0xCmdrKeen** [comment]
Haha, good to know I just wasted half an hour trying to fix it myself, but that's what I get for being impatient I guess 😅
