### ISSUE TITLE
Add option to share links from current instance

### ISSUE THREAD

**Issue by BrianAllred** [Xyphyn/photon#228]
**Is your feature request related to a problem? Please describe.**
When I share a post, it defaults to the original post link. For example, viewing a post on lemmy.world that originated from lemmy.ml and sharing the post will share the lemmy.ml version with no option to share the lemmy.world version.

**Describe the solution you'd like**
An option to share the current instance version of a post.

**Describe alternatives you've considered**
Manually copying the URL of the current instance's version of the post, which is a bit more inconvenient.

**Comment by Xyphyn** [comment]
added in post actions
