### ISSUE TITLE
Expand Images does not zoom the image

### ISSUE THREAD

**Issue by alvarokrn** [Xyphyn/photon#231]
**Describe the bug**
The option to "Expand Images" should open the image in a higher zoom but it just open in almost the same size as is showed in the timeline

**To Reproduce** (if applicable)
1. Go to a post with an image
2. Click on the image
3. The image is shown in almost the same size than in the timeline
4. See the image attached

It happens with all the images that I've seen, not only with the sample of the attached screenshot 

**Expected behavior**
The image should be open expanded in the max size possible of the screen size or at least the original image size. 
The image of the attached  screenshot is shown at 640x470 but the original size of the image is 2048x1504.

**Screenshots**
![Captura de pantalla 2023-12-29 145820](https://github.com/Xyphyn/photon/assets/108217204/a9a869a3-10fe-4c31-b5c0-fe1623170860)
![Captura de pantalla 2023-12-29 150550](https://github.com/Xyphyn/photon/assets/108217204/0ac36cc3-07ee-4b7c-a036-a14e3b002c10)
Link to the Image: https://lemmy.world/pictrs/image/58942777-b9b3-46db-8f13-d29e164afb3e.webp?format=webp

**Versions**
- Browser: Firefox

- Photon version: 1.24.2

**Comment by Xyphyn** [comment]
the size has been increased but i expect you to use browser tools. I dont want to fill the whole screen

**Comment by alvarokrn** [comment]
Thanks! 

I don't know if you already deployed this but now I'm experiencing an even worse issue.

Looks like when I click on a image, the zoomed image is the thumbnail.

I took a few screenshots:


![Captura de pantalla 2024-09-05 092250](https://github.com/user-attachments/assets/3d449621-c77d-42cd-ac26-acd742f527b0)
![Captura de pantalla 2024-09-05 092255](https://github.com/user-attachments/assets/d04858c4-23d0-4da0-8729-b30d70b93b14)
![Captura de pantalla 2024-09-05 092304](https://github.com/user-attachments/assets/d40250c3-272e-4273-9356-572c5ec6ae44)

**Comment by Xyphyn** [comment]
I fixed that too
