### ISSUE TITLE
Make separate buttons for creating posts and communities

### ISSUE THREAD

**Issue by YousufSSyed** [Xyphyn/photon#237]
**Is your feature request related to a problem? Please describe.**
99% of the time when someone clicks the "create" button its to create a new post. It should just be its own button instead of picking between it and creating a new community. Make buttons for both.

**Comment by Xyphyn** [comment]
An entire dedicated button in the navbar to create a community is a bad idea...

**Comment by YousufSSyed** [comment]
How so? The stock Lemmy UI does it:
<img width="550" alt="Screenshot 2024-01-07 at 5 51 43 PM" src="https://github.com/Xyphyn/photon/assets/42646062/bbadd0e5-193a-4a3c-bedb-3d4ab8f28d63">


Maybe a better idea would be to put it in the username dropdown menu, since it's not a commonly used button anyway.
<img width="280" alt="Screenshot 2024-01-07 at 5 51 54 PM" src="https://github.com/Xyphyn/photon/assets/42646062/eb4b1bf9-b316-46e0-933b-2f18c8775fc7">

**Comment by Xyphyn** [comment]
Stock lemmy UI isnt exactly a good way to determine a good design decision

**Comment by YousufSSyed** [comment]
What do u think of the later though. It really doesn't make sense to have a dropdown menu under the create button, if the only other option is something that *literally 99% of users will never click* (or whatever percent of Lemmy users actually end up creating even one community).

**Comment by sant0s12** [comment]
I think I'd put it in the user's drop down menu like on reddit.

**Comment by YousufSSyed** [comment]
That could work

**Comment by Xyphyn** [comment]
I had to look up how to create a community on Reddit one time because I couldn't figure it out, I think maybe I'll keep it like it is for now. + I plan to add more buttons in the future under the create button

**Comment by YousufSSyed** [comment]
What buttons do u plan on adding?

**Comment by Xyphyn** [comment]
im working on a thing that will allow me to create polls that look good on normal lemmy but have special functions and ui on photon

**Comment by Xyphyn** [comment]
I still think it's fine the way it is and i learned with v1.29.0 that navigation changes can be pretty controversial
