### ISSUE TITLE
Add an accent color setting.

### ISSUE THREAD

**Issue by YousufSSyed** [Xyphyn/photon#238]
Photon looks a little bland with the black and white colors. There should be an accent color setting to change the colors of the buttons and make other UI elements different shades of that color. If you decided to implement this, you can allow for picking an RGB or Hex color, or any valid CSS color, including valid `color()` CSS values (that lets you use colors in any valid colorspace, RGB and Hex colors are only for SRGB colors, as described [here](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color)). To make different shades you can use the `lch()` and `from()` CSS color functions.

**Comment by Xyphyn** [comment]
theming added in v1.28.0
