### ISSUE TITLE
Set/Change Account Avatar

### ISSUE THREAD

**Issue by madeofstown** [Xyphyn/photon#241]
**Is your feature request related to a problem? Please describe.**
I currently use photon as my main UI for my lemmy instance and recently noticed there is no way to set or change my account avatar. 
**Describe the solution you'd like**
I would like a setting in my user profile to set/change the account avatar. 

**Describe alternatives you've considered**
Currently the only solution I have is to use lemmy-ui when I want to change my Avatar.

**Comment by sant0s12** [comment]
You can do that here: https://phtn.app/profile/settings under "Profile image".

**Comment by madeofstown** [comment]
> You can do that here: https://phtn.app/profile/settings under "Profile image".

I'm not talking about the profile image. I'm talking about the avatar. The profile image is a banner for your profile page while the avatar is next to your account name in comments and posts.

**Comment by Xyphyn** [comment]
This issue is because my auth system sucks, and i need to update it

**Comment by Xyphyn** [comment]
fixed, it will use your profile and should update
