### ISSUE TITLE
Feature request: Put a toggle switch for light and dark theme on the top bar.

### ISSUE THREAD

**Issue by YousufSSyed** [Xyphyn/photon#247]
Something like this. It would be easy to find and make it quicker to adjust.
![maxresdefault](https://github.com/Xyphyn/photon/assets/42646062/df29e9be-07a1-4e19-a709-d97680dcb825)

**Comment by Xyphyn** [comment]
There's a theme switch in the main menu...

**Comment by YousufSSyed** [comment]
I know, this would be nice to have.

**Comment by sant0s12** [comment]
I think it's fine the way it is now tbh
