### ISSUE TITLE
Highlighting text and pressing 'Link' should turn that text into a link

### ISSUE THREAD

**Issue by Bout2GitIt** [Xyphyn/photon#248]
**Is your feature request related to a problem? Please describe.**
I have this issue when I'm writing out the text of a new post. I'm always frustrated when I highlight words that I want to make into links, then I press the "Link" button, but instead of making my highlighted word into a link, the buttons just creates new text:
`[label](url)the text I want to link` 

**Describe the solution you'd like**
I would like to be able to highlight words, press the link button, and then have those words automatically turn into a hyperlink. For example, I am writing this post right now here on GitHub. If I highlight [these words](photon.lemmy.world) and press the link button, the brackets "[ ]" _automatically_ go around "these words." Try it out! It's great!

**Describe alternatives you've considered**
I have not considered any alternatives.

**Additional context**
I am using Firefox 122 on MacOS 12.1

**Comment by Xyphyn** [comment]
I actually added this with a bug a while ago. If you press ctrl + k it works like how you mention, but the button doesnt do it for some reason. Fixing now
