### ISSUE TITLE
How about embed video in to body post?

### ISSUE THREAD

**Issue by soverxxx** [Xyphyn/photon#249]
How about embed video in to body post? Can you implement this?

**Comment by CTalvio** [comment]
Isn't this already a thing?

Examples: 

https://photon.lemmy.world/post/lemmy.world/4066554

https://photon.lemmy.world/post/lemmy.world/11136719

**Comment by soverxxx** [comment]
Previously, Lemmy allowed you to insert an iframe from YouTube. And it was convenient to share content by creating full-articles.
After that, they removed this feature.

In fact, I think you can make an implementation of what if the user adds, for example, a link "https://www.youtube.com/watch?v=rzUoWR02pAM " in the body of the post - it would be formed in an iframe

**Comment by soverxxx** [comment]
no, I'm talking about some videos inside the body.very useful for reviews and articles.10.02.2024, 01:51, "Casper Talvio" ***@***.***>:
Isn't this already a thing?
Examples:
https://photon.lemmy.world/post/lemmy.world/4066554
https://photon.lemmy.world/post/lemmy.world/11136719

**Comment by Xyphyn** [comment]
Kinda difficult to do and bad for performance because I need to scan every single comment for a youtube link.

I'll consider this tho

**Comment by Xyphyn** [comment]
i did it
