### ISSUE TITLE
Feature Request - Infinite Scrolling, Show the precise date instead of a relative date and hide sidebar toggle on Settings

### ISSUE THREAD

**Issue by dnet890** [Xyphyn/photon#251]
**Is your feature request related to a problem? Please describe.**
it is quite annoying if we need to click next to read our feeds and it is nice we can enjoy reading our feeds completely without  sidebar and also I think it will be great if we can keep tracking our read post accurately on home screen by add a new toggle settings to Show the precise date (i.e: Sun Nov 16 20:14:56 2014 UTC) instead of a relative date (i.e: 7 days ago), for posts and comments

**Describe the solution you'd like**
infinite scrolling like Voyager is quite good. But, it is not nice on desktop

**Describe alternatives you've considered**
Voyager and Liftoff

**Additional context**

**Comment by Xyphyn** [comment]
I've wanted to implement infinite scroll for ages, but sveltekit hasn't added bfcache yet.

https://github.com/sveltejs/kit/issues/9822

This will make it a lot easier for me to add this

For the sidebar, the toggle appears once the screen size is small enough for it to actually matter

**Comment by dtantono** [comment]
I mean for the toggle left side which have lots of communities list. I think it is better if there is a toggle setting to hide it

**Comment by Xyphyn** [comment]
Adding some of the things you mentioned now, thanks for the report! btw, in the future, itd be nice if you could make these things into separate issues instead of like 3 suggestions in 1 issue. Don't worry about creating alot of issues

**Comment by Xyphyn** [comment]
Oh btw, if you hover over a date, it shows the exact one

**Comment by Xyphyn** [comment]
- infinite scrolling exists now
- you can hover over a date for the precise date
- sidebars will stay, but you can collapse everything for cleanliness
