### ISSUE TITLE
docker crash with ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by Tealk** [Xyphyn/photon#252]
**Describe the bug**
I just wanted to run the new update but the container can not start, below I have given the error message

**To Reproduce** (if applicable)
1. Start with command `docker run --name lemmy_photon -p 8081:3000 -e PUBLIC_INSTANCE_URL=rollenspiel.forum -d ghcr.io/xyphyn/photon:latest`

**Expected behavior**

**Log**
```
23 |     console.error(error);
24 |     return new Response("Uh oh!!", { status: 500 });
25 |   }
26 | };
27 | websocket && (serverOptions.websocket = websocket);
28 | var server = serve(serverOptions);
                  ^
TypeError: 湕捩摯⁥潨瑳慮敭⁳畭瑳愠牬慥祤戠⁥湥潣敤⁤潦⁲潮⹷渊睥唠䱒椨灮瑵⸩潨瑳慮敭猠潨汵⁤潤琠敨琠楲正.慢敳剕⁉慣❮⁴慨敶愠甠敳湲浡⁥牯瀠獡睳牯d畢彮敶獲潩灮慬晴牯晭慲敭潷歲牦浡睥牯彫敶獲潩䥮癮污摩
 code: "ERR_INVALID_ARG_TYPE"

      at /app/build/index.js:28:14

Bun v1.1.8 (Linux x64 baseline)
```

**Versions**
- Browser: Firefox
- Photon version: 1.27.0

**Comment by Tealk** [comment]
Still the same problem with v1.27.1

**Comment by ticoombs** [comment]
Confirmed. v1.26.0 only safe version.

**Comment by Tealk** [comment]
still exist in v1.28.1

**Comment by Tealk** [comment]
Would be great if this would be fixed, would like to update

**Comment by Tealk** [comment]
bug still exist in v1.29.1

**Comment by Tealk** [comment]
because i just have time i wanted to test if it works if i create the docker image myself, but i also get the error.

```
docker run --name lemmy_photon -p 8081:3000 -it photon:latest
23 |     console.error(error);
24 |     return new Response("Uh oh!!", { status: 500 });
25 |   }
26 | };
27 | websocket && (serverOptions.websocket = websocket);
28 | var server = serve(serverOptions);
                  ^
TypeError: 湕捩摯⁥潨瑳慮敭⁳畭瑳愠牬慥祤戠⁥湥潣敤⁤潦⁲潮⹷渊睥唠䱒椨灮瑵⸩潨瑳慮敭猠潨汵⁤潤琠敨琠楲正.慢敳剕⁉慣❮⁴慨敶愠甠敳湲浡⁥牯瀠獡睳牯d畢彮敶獲潩灮慬晴牯晭慲敭潷歲牦浡睥牯彫敶獲潩䥮癮污摩
 code: "ERR_INVALID_ARG_TYPE"

      at /app/build/index.js:28:14
note: missing sourcemaps for /app/build/index.js
note: consider bundling with '--sourcemap' to get an unminified traces
```

**Comment by Xyphyn** [comment]
node servers are added for people having issues here. just use `ghcr.io/xyphyn/photon:<version>-node`
