### ISSUE TITLE
Caching of sites for non-logged in users

### ISSUE THREAD

**Issue by poVoq** [Xyphyn/photon#255]
If pages could be served for non-logged in users as static html without hitting the database, that would probably significantly lower the server resource use.

There are some similar plans for lemmy-ui:
https://github.com/LemmyNet/lemmy-ansible/issues/195

Would be cool if this could be supported by Photon. Thanks!

**Comment by CorvetteCole** [comment]
imo, this is out of scope. Caching is a solved problem if you handle it further up the stack. Have your CDN cache requests to the URL that don't have the auth cookie. We do that for lemdro.id

**Comment by CorvetteCole** [comment]
Or even implement it in your reverse proxy such as Nginx.

**Comment by poVoq** [comment]
This is about cache-control headers, which is different from running it behind a privacy violating proxy like Cloudflare.

**Comment by Xyphyn** [comment]
This is up to sveltekit to handle, and i dont think i can control it right now
