### ISSUE TITLE
External links don't open in new tab

### ISSUE THREAD

**Issue by fievel** [Xyphyn/photon#256]
**Describe the bug**
According to #200, external links should always open in new tab. This seems not the case.

**Expected behavior**
External links should open in new tabs whatever state the setting "Open posts in new tab" is. From my tests, it seems not the case (tested in both mode, with open posts in new tab == on the posts open in new tab but external link not (unless middle-clicking but that's a browser shortcut).

**Screenshots**
Here a inspect on one external link from my home feed, there is no target="_blank" or so.
![image](https://github.com/Xyphyn/photon/assets/435110/280d974d-1f99-473f-a1aa-7193a100d6ba)

**Versions**
- Browser: Firefox 115.7.0esr
- Photon version: 1.27.0 (https://phtn.app instance)

**Comment by Xyphyn** [comment]
this was for comments and posts only, adding to these links right now
