### ISSUE TITLE
Can't create a post from main page

### ISSUE THREAD

**Issue by mazury** [Xyphyn/photon#261]
**Describe the bug**
Can't create post from main page.

**To Reproduce** (if applicable)
1. Go to main page of your instance
1. Click create post in top righe
2. choose community, write some title and submit
3. Observe the error popup in bottom right

Creating posts from a community page works well
Ver. 1.27.3

**Comment by Xyphyn** [comment]
fixed, this kids is why you use prerelases and don't put untested versions into production

**Comment by mazury** [comment]
It works for me in 1.27.4. What do you mean is not being build as a new container?

**Comment by Xyphyn** [comment]
It is I rushed
