### ISSUE TITLE
Unblur the video preview image

### ISSUE THREAD

**Issue by mazury** [Xyphyn/photon#262]
**Is your feature request related to a problem? Please describe.**
When I scroll to a post which is a video the video is blurred, it looks like this:
![image](https://github.com/Xyphyn/photon/assets/24698150/d3172909-37d6-4300-b55d-965925b4724f)

People don't know what to expect

**Describe the solution you'd like**
Can we unblur that?

**Comment by Xyphyn** [comment]
that is a placeholder image. this means lemmy did not give me a thumbnail image to use.

**Comment by mazury** [comment]
So it's a lemmy server issue? What data/variable exactly is that so I'll ping lemmy repo

**Comment by Xyphyn** [comment]
Lemmy needs to provide thumbnail URLs for videos

**Comment by Xyphyn** [comment]
PostView.Post.thumbnail_url

**Comment by mazury** [comment]
Ok I think they may have already resolved that and it will be in next release: https://github.com/LemmyNet/lemmy/issues/4468
