### ISSUE TITLE
Can't remove item from federation whitelist

### ISSUE THREAD

**Issue by mazury** [Xyphyn/photon#263]
**Describe the bug**
I click on remove X icon next to an instance and nothing happens

**To Reproduce** (if applicable)
1. In admin panel -> federation, have a blocklist with some instances, have empty whitelist (these are the initial conditions with which I tested)
2. add instance to whitelist
3. refresh, try to remove that instance from whitelist and observe that nothing happens, nothing gets send to the server

**Versions**
- Browser: Brave
- Photon version: 1.27.4

**Comment by Xyphyn** [comment]
you need to click save when you change the list. however there is a bug that makes it only affect blocked instances, so this issue is valid. fixing
