### ISSUE TITLE
Thumbnails are aligned to the left when using list/compact, and below title, regardless of setting

### ISSUE THREAD

**Issue by CTalvio** [Xyphyn/photon#265]
**Describe the bug**
Thumbnails are aligned to the left when using list/compact, and below title, regardless of setting.

**Screenshots**
![image](https://github.com/Xyphyn/photon/assets/4365015/f775367a-27bd-423f-ac37-084bab0fc994)
![image](https://github.com/Xyphyn/photon/assets/4365015/bbce0bcb-44fe-47f5-9489-54813de65c12)

**Versions**
- Browser: Firefox
- Photon version: 0.27.3

**Comment by Xyphyn** [comment]
sorry ive been rushing and super demotivated recently and forgot to fix

**Comment by CTalvio** [comment]
Don't even worry about it.
