### ISSUE TITLE
Per account Photon settings

### ISSUE THREAD

**Issue by BrikoX** [Xyphyn/photon#269]
**Is your feature request related to a problem? Please describe.**
Photon allows multiple accounts to be added and easy switching between them. But they all use the same settings for all of those accounts. 

**Describe the solution you'd like**
Option to use different Photon settings for each attached account. 

**Additional context**
Most instances that offer Photon front end have it limited to their own instance. Self hosting solves that, but I have various accounts that I use in specific ways with different default settings. Now I need to manually switch the views, sort options and other settings every time I switch the account.

**Comment by Xyphyn** [comment]
I don't think this makes sense in the spacial model that photon has right now.

- Accounts are seen as essentially your "token" to access lemmy
- They don't have any _state_
- Settings is under the model of "Application" things, which are global

One of the biggest things i hated about using Sync is that all my accounts had different settings, which was a nightmare to maintain.
