### ISSUE TITLE
Taglines do not support markdown 

### ISSUE THREAD

**Issue by CorvetteCole** [Xyphyn/photon#27]
Thanks for implementing #20 so quickly! I discovered that markdown doesn't seem to be parsed in taglines at the moment
![Screenshot_20230726-143749](https://github.com/Xyphyn/photon/assets/19213965/f017dd0d-b7d2-46d3-8209-22f9c431a0de)

No rush, thanks for your work!

**Comment by Xyphyn** [comment]
oops

**Comment by Xyphyn** [comment]
![image](https://github.com/Xyphyn/photon/assets/80978739/5a575fcd-d21d-4adc-aa50-229f4d79ddee)

on a completely irrelevant note, this is the most folders i've had in any project
