### ISSUE TITLE
Italic and bold text not working in text editor

### ISSUE THREAD

**Issue by mazury** [Xyphyn/photon#271]
**Describe the bug**
Italic and bold text not working in text editor (not sure which tools else, checked only those)

**To Reproduce** (if applicable)
-create post
-add text to post body
-select some text and click bold or italic, text is wrapped in asterisks
- save, observe that asterisks are in post and text is not bolded

1.27.4

**Comment by Xyphyn** [comment]
Can't reproduce

**Comment by mazury** [comment]
Ok looks like the problem is onlin with multilines with empty lines between:

**test**

**test
test**

**test

test**

The last one won't be bolded

**Comment by mazury** [comment]
Oh I didnt know that but it looks like you cant do this in these editor. 
**line1

empty line above, that wont be bolded**

Have to bold each paragraph separately 
Closing this.

**Comment by Xyphyn** [comment]
Ya markdown parsers do that
