### ISSUE TITLE
Documentation how to change the default theme for self-hosting?

### ISSUE THREAD

**Issue by poVoq** [Xyphyn/photon#273]
It seems like right now users can modify the theme individually and can also import theme settings from an external source, but as an instance admin, how to I change the default theme for non-logged in users and those that do not want to modify it themeselves?

**Comment by ngn13** [comment]
With 81ac6ac, `PUBLIC_THEME` has been replaced with `PUBLIC_LEGACYTHEME`, I think @Xyphyn should update the README.

**Comment by poVoq** [comment]
Good point, but that still doesn't explain how to set a default non-legacy theme.

**Comment by Xyphyn** [comment]
That's been added, just use `PUBLIC_THEME` and it's documented.
