### ISSUE TITLE
Photon keeps shooting /user endpoint continuously

### ISSUE THREAD

**Issue by mazury** [Xyphyn/photon#276]
Looks pretty nasty. No matter what page. Here is a video of a post page after refresh:

[Screencast from 09.03.2024 12:37:26.webm](https://github.com/Xyphyn/photon/assets/24698150/0984239e-007f-47b4-9d18-49a2e923e2f2)

**Comment by Xyphyn** [comment]
hotfixed in v1.28.2-hotfix
