### ISSUE TITLE
Wrap generated body from the link in Markdown quote

### ISSUE THREAD

**Issue by BrikoX** [Xyphyn/photon#278]
**Is your feature request related to a problem? Please describe.**
When using a button to generate title/body, it inserts body as plain text. That can give false impression it's the thoughts of the post author instead of the content from the included link. 

**Describe the solution you'd like**
Add a toggle in the settings or change the native behavior to wrap generated body from the link in Markdown quote.

**Additional context**
Right now
![image](https://github.com/Xyphyn/photon/assets/69597682/6f31341c-a607-4d19-9ff6-3e5e6a1a7487)

Proposed
![image](https://github.com/Xyphyn/photon/assets/69597682/32612987-61e7-4721-8053-6d033ecf14a3)

**Comment by Xyphyn** [comment]
adding now
