### ISSUE TITLE
Deleted/removed comments are still shown

### ISSUE THREAD

**Issue by Tywele** [Xyphyn/photon#279]
**Describe the bug**
Deleted or removed comments are still shown under a post with a red trash icon beside the comment header

**To Reproduce** (if applicable)
See here for an example https://lemmy.dbzer0.com/comment/8749884

**Expected behavior**
I expect to not see deleted/removed comments.

**Screenshots**
![Screenshot of the link above in Photon](https://github.com/Xyphyn/photon/assets/8156875/facfff17-3caf-42d5-a311-5ac12114ca89)

**Versions**
- Browser: Firefox
- Photon version: 1.28.1

**Comment by BrikoX** [comment]
It's a configurable setting in Photon. See 
![image](https://github.com/Xyphyn/photon/assets/69597682/c5cce35d-656d-42cb-bac3-fffeb84cfeea)

**Comment by Tywele** [comment]
They are turned on for me
![grafik](https://github.com/Xyphyn/photon/assets/8156875/a6877df9-441c-4f4e-bef1-fe83cbe4b517)

**Comment by Tywele** [comment]
This should definitely be an option wether you want to still see deleted/removed comments or not. Just like for posts.

**Comment by Xyphyn** [comment]
i forgot this option still existed and while cleaning code i accidentally removed this. re-adding right now

**Comment by Xyphyn** [comment]
Would you like deleted/removed comments to have the child comments hidden as well?

**Comment by Tywele** [comment]
No child comments should still be visible

**Comment by poVoq** [comment]
There is either a regression on this in the current version (1.28.4), or this is still broken.

It is especially odd that posts that a moderator deleted get still shown to everyone, even not logged in users.
