### ISSUE TITLE
Gap between hostname and pathname in embed-less links

### ISSUE THREAD

**Issue by BrikoX** [Xyphyn/photon#280]
In https://github.com/Xyphyn/photon/commit/051c4c5a6245d9fb6cf428d95b2b889bf9456427 the way embed-less links are displayed was changed. One of the changes was adding `.gap-1` class which makes reading links a lot harder, especially in compact view. Could this be reconsidered? 

Example 
![image](https://github.com/Xyphyn/photon/assets/69597682/c5ff09ed-636c-40b0-8f32-9bb5fc09e4d9)

**Comment by Xyphyn** [comment]
This was fixed in the most recent pre-release. You can see it on phtn.app
