### ISSUE TITLE
Add a setting to hide community description from the list

### ISSUE THREAD

**Issue by BrikoX** [Xyphyn/photon#281]
**Is your feature request related to a problem? Please describe.**
In https://github.com/Xyphyn/photon/commit/b79496a1c928118da9ef4d1d52a048ef10d81f57 the change was made to include community description in the /communities list. Since the description is from the community sidebar and it parses the markdown, the list now looks very chaotic. 

**Describe the solution you'd like**
Add an optional setting to hide the community description in the /communities list. 

**Additional context**
v1.26.0
![image](https://github.com/Xyphyn/photon/assets/69597682/2a921f49-fb35-40bc-adb5-318c9901ac25)

v1.28.3
![image](https://github.com/Xyphyn/photon/assets/69597682/d82437d2-9472-4a35-803e-e670c87eaa1a)

**Comment by gapetto** [comment]
Could be folded by default and expandable with some button

**Comment by BrikoX** [comment]
> Could be folded by default and expandable with some button

That's an option, we kind of already have that with i button. 
![image](https://github.com/Xyphyn/photon/assets/69597682/a1872019-ee94-434c-aadc-99d16a516d12)

**Comment by Xyphyn** [comment]
The entire communities component was redesigned, and has no body by default.
