### ISSUE TITLE
Add ability to pin communities

### ISSUE THREAD

**Issue by gapetto** [Xyphyn/photon#286]
We have currently subscribed section. There could pinned section above, where there are few of our most used communities that we choose (similar to facebook group pinning functionality)

(Or maybe some other mechanism that will allow to quickly go to communities that we use / like the most?)

**Comment by cloudlessx** [comment]
This. This only thing I miss from Voyager is "favourite" communities. Photon is better overall but I wish it would add pin/favourites.

**Comment by Xyphyn** [comment]
You can do that now in the sidebar by hovering over the community icon. And to get to any communtiy quickly, just use the command palette
