### ISSUE TITLE
Exclamation marks shown in feed when images are embedded in post body

### ISSUE THREAD

**Issue by cloudlessx** [Xyphyn/photon#288]
**Describe the bug**
Exclamation marks shown in feed when images are embedded in post body

**To Reproduce** (if applicable)
1. Go to https://phtn.app/c/ukraine@sopuli.xyz
2. Find the post with the title "A Russian Su-27 was reportedly..."
3. See the !!!! marks under the thumbnail

Images are displayed without exclamation mraks when visiting the post directly:
https://phtn.app/post/lemmy.cafe/3853805

**Expected behavior**
Do not display the exclamation marks

**Screenshots**
![image](https://github.com/Xyphyn/photon/assets/159134845/7c8b1d46-563c-4d60-b721-5a43d495ccd7)

**Versions**
- Browser: Firefox
- Photon version: 1.28.5 (phtn.app)

**Comment by Xyphyn** [comment]
Fixed.
