### ISSUE TITLE
Remove duplicate display of link title

### ISSUE THREAD

**Issue by cloudlessx** [Xyphyn/photon#289]
**Is your feature request related to a problem? Please describe.**
You see the exact same title twice in all link posts. 

Example:
![image](https://github.com/Xyphyn/photon/assets/159134845/e84befc1-42c7-4c78-80fa-9791ba9e2e3e)

**Describe the solution you'd like**
Show the article title in the header only.

**Describe alternatives you've considered**
Use full-size card instead of thumbnail for links. Like what Voyager does. Perhaps making it an option?

**Additional context**
How Voyager does it:
![image](https://github.com/Xyphyn/photon/assets/159134845/f5b19790-c106-4515-80bf-8ee56c1c8c11)

**Comment by BrikoX** [comment]
One is user title another is <title> element from the link. One can be modified by the user, another can't. 

It's just commonly the same due to generate title feature on Photon and similar functionality in other clients.

**Comment by cloudlessx** [comment]
@BrikoX While I understand the logic behind the design, there is a reason why every other client (and kbin) UI display only one of the titles in the feed. 

Web UI like Lemmy UI, Voyager, Alexandrite, Kbin, Mbin. Apps like Eternity, Raccoon for Lemmy... just to name a few. They all display only the post title by default, some with a button that you can use to expand and see the article title.

I am all for letting the users see more information. But in this case the titles become redundant when the user is trying to browse the feed.

**Comment by Xyphyn** [comment]
i added this a while ago, but some people complained so i removed it, now we're back to this lol

ill just make it an option

**Comment by cloudlessx** [comment]
@Xyphyn How about you make an option that hides the article title if it is the same as the post title? Something like:

if(article.title == post.title) 
{
   article.title.setVisbility(false);
}
