### ISSUE TITLE
Unable to play embedded YouTube videos

### ISSUE THREAD

**Issue by Tywele** [Xyphyn/photon#291]
**Describe the bug**
It's impossible to view embedded YouTube videos. When hitting play the error shown in the screenshot is displayed.

**To Reproduce** (if applicable)
1. Go to https://p.lemmy.dbzer0.com/post/lemmy.dbzer0.com/17771148 for example
2. Hit play
3. See error like in screenshot

**Expected behavior**
Working YouTube video

**Screenshots**
![YouTube error](https://github.com/Xyphyn/photon/assets/8156875/719a57f8-676c-4526-a265-634d5ca542d7)

**Additional info**
I already tried with no browser extensions enabled and it shows the same error.

**Versions**
- Browser: Firefox
- Photon version: 1.28.1

**Comment by BrikoX** [comment]
It's probably YouTube blocking embedded playback. It's an option creators can check when uploading a video.

**Comment by Tywele** [comment]
That would mean that it shouldn't work on the default lemmy ui as well but it's working there.

**Comment by CTalvio** [comment]
Photon isn't embedding youtu.be share links correctly. Normal youtube.com links work.

**Comment by Xyphyn** [comment]
I think it works now

**Comment by CTalvio** [comment]
yup
