### ISSUE TITLE
Increase default post height and retain height when switching between Edit and Preview mode.

### ISSUE THREAD

**Issue by QazCetelic** [Xyphyn/photon#294]
**Is your feature request related to a problem? Please describe.**
The edit field is too small to easily edit larger posts, and switching between Edit and Preview mode shrinks it again after manually increasing the height.

**Describe the solution you'd like**
1. Retain height when switching between Edit and Preview mode. 

2. Increase default height.
![image](https://github.com/Xyphyn/photon/assets/51381523/7fbfc88a-d033-4c24-aa12-28418de1a76d)

**Describe alternatives you've considered**
1. Retaining the size when switching, without increasing it by default.
2. Stop caring about it

**Comment by Xyphyn** [comment]
I instead changed it so that the textarea will expand as you type.
