### ISSUE TITLE
Top buttons in profile are unclickable

### ISSUE THREAD

**Issue by Tywele** [Xyphyn/photon#297]
**Describe the bug**
The buttons for "User", "Settings", "Blocks" and "Credentials" at the top of the profile page are unclickable

**To Reproduce** (if applicable)
1. Go to Profile
2. Try to click one of the buttons

**Expected behavior**
I expect that the buttons brings me to the corresponding page.

**Screenshots**
![Screenshot of profile header containing the buttons](https://github.com/Xyphyn/photon/assets/8156875/5cf36b48-c049-4102-8160-759f7e8ab4c8)

**Versions**
- Browser: Firefox
- Photon version: 1.28.1

**Comment by Xyphyn** [comment]
you're using an outdated photon version.
