### ISSUE TITLE
Trim some <a> tags to prevent accidental preloading of content

### ISSUE THREAD

**Issue by BrikoX** [Xyphyn/photon#298]
**Is your feature request related to a problem? Please describe.**
When scrolling a home feed or a community, if you scroll by any title it preloads the content and marks it as read. That is not a problem, but since the <a> tag for title spans the full width on main body area, it makes it almost impossible to not accidentally mark something as read.

_P.S. The same is is true for community name link, but it doesn't have adverse affect of being marked as read._

**Describe the solution you'd like**
Use something like `max-width: fit-content;` so that <a> tag ends with the content instead of spanning the whole main body area. 

**Additional context**
![image](https://github.com/Xyphyn/photon/assets/69597682/30ae98b8-bbae-4857-8129-0f4356418e62)
![image](https://github.com/Xyphyn/photon/assets/69597682/faa00381-f17a-4486-93fd-4e9e405be01f)

Examples are provided in compact view mode, but the same is true for other modes.

**Comment by Xyphyn** [comment]
It shouldn't mark things as read accidentally anymore.
