### ISSUE TITLE
Markdown of lists is not properly displayed

### ISSUE THREAD

**Issue by Tywele** [Xyphyn/photon#299]
**Describe the bug**
List markdown is not properly displayed see screenshot

**Expected behavior**
The text beside a bullet point should start in the same line.

**Screenshots**
![grafik](https://github.com/Xyphyn/photon/assets/8156875/496ec34d-e03f-4cfe-92a2-4ff8ef772802)

**Versions**
- Browser: Firefox
- Photon version: 1.28.1

**Comment by Xyphyn** [comment]
css + markdown is a curse upon humanity

**Comment by Xyphyn** [comment]
trying to fix but i cant figure out how

**Comment by Tywele** [comment]
Before: 
![grafik](https://github.com/Xyphyn/photon/assets/8156875/20a75772-c8e6-4154-bd33-9038ef30bbbb)

After: 
![grafik](https://github.com/Xyphyn/photon/assets/8156875/ad1fdd1e-a143-43e2-a6b8-dee1f7c5568f)

Achieved by removing `whitespace-pre-wrap` class here:
![grafik](https://github.com/Xyphyn/photon/assets/8156875/c71b8745-7a97-41b7-8bca-f626989aa47b)

Don't know how much that helps you and what else this is changing but this seems to be one way of fixing it.

**Comment by Xyphyn** [comment]
No clue what was happening but it seems to be fixed now.
