### ISSUE TITLE
Container image

### ISSUE THREAD

**Issue by CorvetteCole** [Xyphyn/photon#3]
Hello, I'd love to throw this up as an alternative frontend option on https://lemdro.id, but I don't have the time right now to package it up myself. A Docker container or something like it could be easily deployed by me, thanks!

**Comment by Xyphyn** [comment]
Currently this only works as a standalone client as there isn't an easy option to change the default instance URL. I'll add an environment variable perhaps. I'm planning to do this with my own instance too.

**Comment by CorvetteCole** [comment]
That's great, this is an awesome UI good work! If you plan on adding mod tools we may make this the default UI at lemdro.id eventually

**Comment by Xyphyn** [comment]
Done adding docker
