### ISSUE TITLE
Empty space below a post when arriving from the frontpage on Safari iOS

### ISSUE THREAD

**Issue by blox814123** [Xyphyn/photon#304]
**Describe the bug**

When arriving from the frontpage and clicking on a post, the page is too long and there is a lot of empty space. Refreshing takes care of the issue. This only happens on mobile.

**To Reproduce**

1. Go to phtn.app
2. Click on a random post
3. Scroll down to the bottom of the page
4. See empty parts of the page
5. Refresh page
6. No longer see empty parts of the page

**Expected behavior**

The page should end with the content.

**Screenshots**

<img width="375" alt="photonbug" src="https://github.com/Xyphyn/photon/assets/83985490/c3aa19e7-54f8-4a26-af80-69f54af0706c">

**Versions**
- Browser: Safari, Iphone
- Photon version: 1.29.0

**Comment by blox814123** [comment]
I generally noticed that photon is pretty buggy on iOS and I assume that testing is done via Android browsers.

**Comment by Xyphyn** [comment]
> I generally noticed that photon is pretty buggy on iOS and I assume that testing is done via Android browsers.

Apple gives 0 craps about following CSS and HTML standards and there's so many bugs on it that I don't even care about supporting Safari at this point. Also, thanks to Apple requiring a Mac or an iPhone to even use Safari, I can't test this. I'll try and fix some major issues like this though.

**Comment by Xyphyn** [comment]
Is this issue still present? If so, re-open this issue.
