### ISSUE TITLE
Crossposts contain redundant information

### ISSUE THREAD

**Issue by blox814123** [Xyphyn/photon#306]
Instead of the URL, which is redundant, it should contain the number of comments and upvotes.

In addition, crossposts should probably be collapsed by default, because the information is only relevant if you actually want to look at the crossposts instead of the comments on the given post.

![image](https://github.com/Xyphyn/photon/assets/83985490/f93cd975-6ee0-4d02-b68c-3ea3ebb171d7)

**Comment by Xyphyn** [comment]
Fixing in v1.29.1

**Comment by prezmix** [comment]
Crosspost expanding is broken in List/Compact modes.
