### ISSUE TITLE
Posts should be clickable as blocks

### ISSUE THREAD

**Issue by blox814123** [Xyphyn/photon#307]
There is no way to actually click through to this example post, except by clicking on the comments button, since the title got removed due to the duplicate post title and URL title.

Posts should be clickable as an entire block (this is how reddit does it).

![image](https://github.com/Xyphyn/photon/assets/83985490/d1893bc9-da57-4773-84c9-189e372879f6)

**Comment by Xyphyn** [comment]
You can but it's inconsistent, because this is actually pretty difficult while not breaking HTML guidelines.

**Comment by Xyphyn** [comment]
I now allow you to click through the post body which should make this a lot more noticable.

**Comment by prezmix** [comment]
> I now allow you to click through the post body which should make this a lot more noticable.

This doesn't seem to work in Cozy view, especially when hideTitle comes into play.
