### ISSUE TITLE
 Improvements for the inbox

### ISSUE THREAD

**Issue by blox814123** [Xyphyn/photon#308]
I suggest some improvements for the inbox. As a start, by default all messages should be visible, not just unread. The current setup makes it difficult to keep track of messages.

- Messages should be grouped by conversations (all replies should go into one conversation)
- Writing messages on photon should be consistent with the comment function, instead of using overlays/modals

**Comment by Xyphyn** [comment]
There is a dedicated messages page now `/inbox/messages`
