### ISSUE TITLE
Editing a NSFW post remove the NSFW 

### ISSUE THREAD

**Issue by Krafting** [Xyphyn/photon#311]
**Describe the bug**

Hello, I've just found out that editing a NSFW post, it disable the NSFW checkbox, so when you save your edit, the post is no longer marked as NSFW

**To Reproduce** (if applicable)
1. Post something as NSFW
2. Edit the post using Photon
3. Notice the NSFW checkbox is unckecked

**Expected behavior**

If the post is NSFW, the checkbox should be ON by default when editing the post

**Versions**
- Browser: Firefox
- Photon version: 1.29.1 
- Instance: lemmy.world

**Comment by Xyphyn** [comment]
Fixed in v1.29.3
