### ISSUE TITLE
Cannot login if password is longer than 60 characters.

### ISSUE THREAD

**Issue by sevonj** [Xyphyn/photon#312]
**Describe the bug**
I gave my lemmy account a long password. I can login through other frontends (Lemmy-UI, Voyager), but not Photon. I tested quite a few passwords and found that 60 characters works, but anything longer gives "Incorrect login," with correct password.

**To Reproduce** (if applicable)
1. Change password in Lemmy-UI, to 61 characters or longer
2. Try to login via Photon

**Expected behavior**
A successful login.

**Screenshots**
![Screenshot from 2024-05-15 14-38-19](https://github.com/Xyphyn/photon/assets/100710152/76d3675c-957e-4e4f-bf0c-bce1e645d431)

**Versions**
- Browser: Firefox
- Photon version: 1.29.3

**Comment by sevonj** [comment]
Well I found out what's actually going on, 5 minutes _after_ filing this issue.

Max password length is 60 characters. The input fields on lemmy-ui silently truncated my passwords to <= 60 characters.

I guess the issue is now reduced to a suggestion: 
Limit login password field to 60 characters and maybe let the user know if they're trying to input a too long password.

**Comment by neatchee** [comment]
> Well I found out what's actually going on, 5 minutes _after_ filing this issue.
> 
> Max password length is 60 characters. The input fields on lemmy-ui silently truncated my passwords.
> 
> I guess the issue is now reduced to a suggestion: Limit login password field to 60 characters and maybe let the user know if they're trying to input a too long password.

Thank you for posting this comment. This just saved me after HOURS of troubleshooting. Slightly annoyed that my password got truncated and every other application just silently handled it 🤷
