### ISSUE TITLE
A refresh button on the inbox page would be very helpful

### ISSUE THREAD

**Issue by 0xCmdrKeen** [Xyphyn/photon#313]
**Is your feature request related to a problem? Please describe.**

I mainly use Photon in a chromeless browser environment (Ferdium), and something that bugs me is that there is no easy way to access new messages when I'm already in the inbox view. I always have to navigate away to a different page and then click on the inbox link again if I want to see my updated messages. 

**Describe the solution you'd like**

A simple reload button next to "Mark All Read" that only makes the requisite API call to fetch new messages and update the view would be helpful.

**Describe alternatives you've considered**

In a regular browser, I suppose I could just use the browser's reload function, but in Ferdium, that would just end up bringing me back to the front page again, so it's basically no different from navigating somewhere else. Also, it does seem rather wasteful since all that would be required to load new messages is an API call, but reloading the entire window would cause the entire app to bootstrap itself again.

**Comment by Xyphyn** [comment]
I'll add this

**Comment by 0xCmdrKeen** [comment]
Awesome, I see it's live now. Thank you so much.
