### ISSUE TITLE
Login error is displayed in notification as JSON

### ISSUE THREAD

**Issue by notramo** [Xyphyn/photon#314]
![image](https://github.com/Xyphyn/photon/assets/26059643/bb593426-fdd0-465b-9a87-5ce785c8ef00)

I also suggest displaying as an alert above the "log in" button instead of a notification, to avoid [change blindness](https://www.nngroup.com/articles/change-blindness-definition/).

**Comment by 0xCmdrKeen** [comment]
This goes for other error messages as well, such as posting to a community which you're banned from.

**Comment by Xyphyn** [comment]
Thanks for the feedback on change blindness, I'll be updating parts of the UI to fix that soon.

**Comment by Xyphyn** [comment]
It should be better now for login errors. I also localized some error messages for easier readability.
