### ISSUE TITLE
List view - Title missing on some YouTube links.

### ISSUE THREAD

**Issue by sevonj** [Xyphyn/photon#317]
**Describe the bug**
In list view, post titles are missing for YT links. See screenshot.

**To Reproduce** (if applicable)
1. Browse https://phtn.app/c/videos@lemmy.world in list view.

**Expected behavior**
The title is shown.

**Screenshots**
![image](https://github.com/Xyphyn/photon/assets/100710152/1b33d92c-992f-40af-aba0-ace3742463f9)

**Versions**
- Browser: Tested Firefox and Chromium, on desktop and android.
- Photon version: 1.29.3

**Comment by prezmix** [comment]
Per `src/lib/components/lemmy/post/Post.svelte` the `hideTitle` logic is intentional though do not understand it as is because the  title is hidden in _List_ view mode or when _Click to View_ option is enabled...

As a workaround you can set `PUBLIC_DEDUPLICATE_EMBED=false` .
