### ISSUE TITLE
Expanding crossposts on index/frontpage is broken for "list" and "compact" modes

### ISSUE THREAD

**Issue by blox814123** [Xyphyn/photon#320]
**Describe the bug**
Expanding crossposts on index/frontpage is broken for "list" and "compact" modes

**Comment by Xyphyn** [comment]
What's broken about it? It works on v1.29.3 for me

**Comment by prezmix** [comment]
Testing 1.29.3, in Cozy or Legacy view mode it works as intended, when cross post is expanded:

![image](https://github.com/Xyphyn/photon/assets/19703660/a4a0a509-c353-4675-8c25-79439970c01d)

then switching to List, or Compact you get this:

![image](https://github.com/Xyphyn/photon/assets/19703660/64b0e9eb-3b20-4522-a18a-eb82effe00a7)

**Comment by prezmix** [comment]
This can be confirmed on the official instance as well. 

For example, go to https://phtn.app/c/technology@lemmy.world and expand any cross post in Compact/List view mode, eg.

![image](https://github.com/Xyphyn/photon/assets/19703660/756c0b55-998e-43fc-9509-bada8768aa66)

![image](https://github.com/Xyphyn/photon/assets/19703660/af38fba9-ad73-44e1-9b3c-d8f4b94f07f9)

**Comment by prezmix** [comment]
Seems this only affects Safari and Chrome based browsers. Firefox is ok.

**Comment by Xyphyn** [comment]
That's why I didn't notice the problem. fixing soon

**Comment by Xyphyn** [comment]
Chrome strikes again

**Comment by Xyphyn** [comment]
This shouldn't happen anymore
