### ISSUE TITLE
Implement internationzalization

### ISSUE THREAD

**Issue by Tmpod** [Xyphyn/photon#325]
**Is your feature request related to a problem? Please describe.**
I run a regionalized instance and would love to translate Photon to my language.

**Describe the solution you'd like**
Photon should be translatable either manually or ideally through platforms like Weblate.

**Describe alternatives you've considered**

--

**Additional context**

 --

**Comment by poVoq** [comment]
Also really cool would be client side auto-translation of posts: https://github.com/Xyphyn/photon/issues/146

**Comment by Xyphyn** [comment]
#239

**Comment by Xyphyn** [comment]
> Also really cool would be client side auto-translation of posts: #146

Thanks to CORS I can't do this. I hate CORS. CORS is the worst idea in the history of the internet. Seriously, what use does it have? It has never helped me. It has never saved leaked credentials. Why is there no way for the user to explicitly allow CORS requests? CORS has no purpose. CORS is useless. CORS is the most worthless thing that I've ever seen. I would rather be stoned to death than have CORS continue to exist. CORS is made to limit what I desire to do. CORS is designed to limit human freedom, and accustom us to authoritarian leadership. CORS is propaganda for totalitarianism. If CORS did not exist, we could have created amazing things. CORS is a limit on our ability to create. CORS prevents the main unique feature of the human species. Creativity is dead thanks to CORS. I will dedicate the remainder of my lifespan hunting down the person whose brain generated the thought of making this scourge. I hope their heart gets a CORS error trying to share blood with their brain.

**Comment by Xyphyn** [comment]
yeah or they use something other than deepl translate

im gonna use libretranslate which works

**Comment by Xyphyn** [comment]
Completed in v1.30.0
