### ISSUE TITLE
Locked instance mode: Broken guest users

### ISSUE THREAD

**Issue by sevonj** [Xyphyn/photon#328]
**Describe the bug**
Trying to add a guest user doesn't work, displays error message.

**To Reproduce** (if applicable)
- Go to some instances photon front
- Try to add a guest user

**Expected behavior**
Not have it fail.

However, I don't see a point in having multiple guests for the same instance. So, instead of fixing this bug, I propose disabling this feature altogether in locked instance mode, and possibly leaving one hardcoded guest user for a "not logged in" state.

Tasks:
- [x] Hide remaining guest login actions #379 
- [ ] Disable /login/guest route.  
(Is there an easy way to just return 404 based on vars?)

**Screenshots**
![image](https://github.com/Xyphyn/photon/assets/100710152/67278f35-347a-4d67-a965-d66234a57d54)

**Versions**
- Browser: Firefox
- Photon version: 1.30.1

**Comment by Xyphyn** [comment]
> Side note: the instance URL might be a tad redundant in the account list.
> ![image](https://github.com/Xyphyn/photon/assets/100710152/870e7143-f0aa-4097-87d5-da09f1d1aecb)
> 

Oh never thought of that thanks

**Comment by Xyphyn** [comment]
I disabled the /login/guest route for v1.31.2
