### ISSUE TITLE
Surface moderator actions to admins, regardless of mod status

### ISSUE THREAD

**Issue by CorvetteCole** [Xyphyn/photon#34]
Instance admins have full access to moderation tools on all communities hosted on their local instance regardless of mod status. It would be great to show the moderation button in this case as well!

 Thanks again for your hard work! Can attach a screenshot if needed.

**Comment by Xyphyn** [comment]
All i'd have to do is append to the `isMod()` check is ` || me.local_user_view.person.admin && community.local`
