### ISSUE TITLE
Distinguish post / speak as moderator

### ISSUE THREAD

**Issue by Tmpod** [Xyphyn/photon#343]
**Is your feature request related to a problem? Please describe.**  
As a moderator of some communities, I sometimes want to distinguish comments related to mod actions.

**Describe the solution you'd like**  
A button under the shield menu to allow distinguishing contents, as well as a checkbox in the comment composer to allow posting comments as moderator right away.

**Describe alternatives you've considered**
Some other UI, perhaps without the checkbox mentioned? Would be useful though.

**Additional context**  
The official UI already impmements this feature.
Docs for the endpoint are here: https://lemmy.readme.io/reference/post_comment-distinguish

**Comment by Xyphyn** [comment]
Yeah I need to work on all 0.19.4 features but currently I'm not home

**Comment by Xyphyn** [comment]
added in v1.31 something
