### ISSUE TITLE
Community icons are getting squished

### ISSUE THREAD

**Issue by Tywele** [Xyphyn/photon#345]
**Describe the bug**
Community icons are gettings squished in the sidebar

**Screenshots**
![grafik](https://github.com/Xyphyn/photon/assets/8156875/22c985d2-4248-40d5-b21a-d5d2215c8083)

**Versions**
- Browser: Firefox
- Photon version: 1.30.3

**Comment by sevonj** [comment]
Related: #338 

That change affects all avatars. An alternative limited scope fix would be to only stop shrinking specifically here
https://github.com/Xyphyn/photon/blob/005a8c0e078bac6144866aa4dda8be514a27f582/src/lib/components/lemmy/community/CommunityCard.svelte#L203-L209
and here

https://github.com/Xyphyn/photon/blob/005a8c0e078bac6144866aa4dda8be514a27f582/src/lib/components/lemmy/SiteCard.svelte#L31-L37
