### ISSUE TITLE
Bug: Compact PostLink wraps in wrong places.

### ISSUE THREAD

**Issue by sevonj** [Xyphyn/photon#355]
**Describe the bug**
Compact view only. The highlighted domain portion can wrap. See screenshot.

**To Reproduce** (if applicable)
 - The offending post: https://phtn.app/post/lemm.ee/36306403

**Expected behavior**

**Screenshots**
![image](https://github.com/Xyphyn/photon/assets/100710152/496304db-9a98-4427-a3f6-09f671930444)
![image](https://github.com/Xyphyn/photon/assets/100710152/1480a838-c5ab-45f2-ab2a-9a92d4e39300)

**Versions**
- Browser: Firefox
- Photon version: 1.30.4

**Comment by Xyphyn** [comment]
the infinite scroll update includes a better link component that shouldn't wrap

**Comment by sevonj** [comment]
Closing as it's now merged.
