### ISSUE TITLE
Show scrollbar like original Lemmy

### ISSUE THREAD

**Issue by dtantono** [Xyphyn/photon#357]
**Is your feature request related to a problem? Please describe.**
it is quite annoying that sometimes if we looking for post and it is hard to track where we scroll the website

**Describe the solution you'd like**
the presence of scrollbar on the right side of the browser like original Lemmy will be helpful

**Describe alternatives you've considered**
OG lemmy UI

**Additional context**

**Comment by Xyphyn** [comment]
The scrollbar is there though? Could you show me it missing?

**Comment by dtantono** [comment]
<img width="803" alt="2024-07-10_11-22" src="https://github.com/Xyphyn/photon/assets/29157187/4a9d0aea-d537-4813-bce8-a8815bac835b">
<img width="953" alt="2024-07-10_11-21" src="https://github.com/Xyphyn/photon/assets/29157187/f7cc8c52-2b2f-4001-b289-7e38ba03fe42">
These pictures are the comparison. What do you think?

**Comment by Xyphyn** [comment]
I recolored the scrollbar but seems like it's not visible here. I'll change that

**Comment by Xyphyn** [comment]
The scrollbar is there, not sure what the issue is

**Comment by dtantono** [comment]
@Xyphyn it looks like the scrollbar is much more visible on Firefox than the Chromium. Since chrome have bigger marketshare than Firefox. Can you make it feature parity?
