### ISSUE TITLE
Expanding comments won't work on Lemmy 0.18.3

### ISSUE THREAD

**Issue by pbui** [Xyphyn/photon#36]
Since updating lemmy to 0.8.13, I am experiencing errors loading comments again.

For instance, using `photon.xylight.dev` through the default `lemm.ee` instance to access  

https://photon.xylight.dev/post/lemm.ee/2185825

When clicking on `5 more` to expand the comments, I get a "Failure to fetch comments" toast.  Looking at the networking output, it appears that the JSON is being delivered properly.

![Screenshot from 2023-07-28 15-49-40](https://github.com/Xyphyn/photon/assets/3976244/12cb1041-5b28-42b6-8d63-6666b2627262)

I augmented the current Photon to simply log a console message of the error and attempting to do the same thing, it appears that result of `buildCommentTree(...).find(...)` is `undefined` and that is why it is failing.

![Screenshot from 2023-07-28 15-54-48](https://github.com/Xyphyn/photon/assets/3976244/5ef54ecc-c918-4efd-bf19-3271e22a7a4b)

What is puzzling is that if I switch to an instance running `0.18.2` such as `lemmy.world`, loading comments works fine.

I also tested this with `lemdro.id` and was able to observe the same behavior:

![Screenshot from 2023-07-28 15-56-35](https://github.com/Xyphyn/photon/assets/3976244/c6fcbd7e-7c5d-4d62-92fc-a064d5a0be07)

What is puzzling is that if I switch to an instance still running `0.18.2` such as `lemmy.world` (at the time of this issue), loading comments works fine.

**Comment by pbui** [comment]
Looking into it more... the `find` is failing to find any matches because all the `c.comment_view.comment.id == parent.comment_view.comment.id` comparisons are failing (different values), which explains why the result is `undefined`.

**Comment by Xyphyn** [comment]
What are some other instances running 0.18.3? Does it fail on those too?

**Comment by Xyphyn** [comment]
If so, I already have the fix implemented and am ready to push.

**Comment by Xyphyn** [comment]
The issue is inconsistent, seems like an issue on Lemmy's end

**Comment by pbui** [comment]
Yes, I've noticed that sometimes it does work, but most of the time it fails.  `lemmy.ml` and `feddit.de` are also on `0.18.3` now.

**Comment by Xyphyn** [comment]
I think my fix is working, this is what I'm doing:

```ts
const tree = buildCommentsTree(newComments.comments, false)

      // 0.18.2 -> 0.18.3 broke this
      // so i'm adding this check
      const treeParent = tree.find(
        (c) => c.comment_view.comment.id == parent.comment_view.comment.id
      )

      console.log('tree parent', treeParent)
      console.log('actual tree', tree)

      if (treeParent) {
        // < 0.18.3
        parent.children = treeParent.children
      } else {
        // 0.18.3+
        parent.children = tree
      }
```

**Comment by Xyphyn** [comment]
the truth is, i have no idea why this works since it doesn't make sense but whatever

**Comment by Xyphyn** [comment]
Can you check if #37 fixes this? Vercel should have deployed a preview link

**Comment by pbui** [comment]
Fixed in #37

**Comment by pbui** [comment]
Hmm, as of 05fcbf0 (v0.4.2), there are no errors, but the comments do not appear on the page.

**Comment by Xyphyn** [comment]
@pbui Do the issues occur on any previous builds? (Commits will have a check next to them, check if vercel has a deployment for them.)

I've been trying to track down this issue, and can't. I believe this is an issue with Lemmy itself

**Comment by Xyphyn** [comment]
If someone manages to fix it you claim the bounty of my sincere appreciation.

**Comment by Xyphyn** [comment]
This issue has to do with how expanding comments works- it builds a sub tree and appends it onto the parent comment in Comments.svelte. If isParent is set to true when calling the function, only one comment is shown, and nothing happens when set to false. I copied the function from Lemmy-ui and am still tracking the issue down.

**Comment by pbui** [comment]
It works better with 590eedc, but still seeing it fail silently on some pages.

**Comment by Xyphyn** [comment]
It fails when it has to fetch a comment of depth higher than 1

**Comment by pbui** [comment]
I think I got it working... incoming PR.
