### ISSUE TITLE
v1.31.0 breaks site for non-logged in users

### ISSUE THREAD

**Issue by poVoq** [Xyphyn/photon#363]
When trying to navigate to the our Photon instance as a user that is not already logged in from a previous pre-1.31.0 visit, all the site shows it a photon logo and the spinning circle.

**Comment by Xyphyn** [comment]
I can't reproduce this error. What instance are you using? Are there any errors in the developer console?

**Comment by poVoq** [comment]
https://photon.slrpnk.net/

There are some errors in the console. It was working until the container update today and is still working when you are logged in already.

I tested with LibreWolf, Firefox and Chromium.

**Comment by Xyphyn** [comment]
Thanks, I think I found the issue.

**Comment by Xyphyn** [comment]
I pushed v1.31.0-fix.1 and the docker image will be available soon, let me know if that fixes this

**Comment by poVoq** [comment]
Yes, fixed.
