### ISSUE TITLE
After Chinese users register, the language does not automatically change to Chinese.

### ISSUE THREAD

**Issue by qiancsff** [Xyphyn/photon#382]
After Chinese users register, the language does not automatically change to Chinese.

中国的中文用户注册后，语言没有自动变为中文
![中国的中文用户注册后，语言没有自动变为中文](https://github.com/user-attachments/assets/ada7fa71-9216-428c-810a-9ca1ff4b45c1)

**Comment by Xyphyn** [comment]
Photon will automatically use the user's preferred browser language, so change that.

**Comment by qiancsff** [comment]
> Photon 将自动使用用户首选的浏览器语言，因此请更改该语言。

My Google Chrome browser has Chinese set as the default preferred browser language.

**Comment by qiancsff** [comment]
My Google Chrome browser has Chinese set as the default preferred browser language.

**Comment by qiancsff** [comment]
> Photon will automatically use the user's preferred browser language, so change that.

My Google Chrome browser has Chinese set as the default preferred browser language.

**Comment by Xyphyn** [comment]
Hmm, I think I know the problem. I will fix soon

-------- Original Message --------

**Comment by Xyphyn** [comment]
I have added aliases for languages in the next release, which should fix this if you're using auto.
