### ISSUE TITLE
On the post editor, there is an redundant symbol.

### ISSUE THREAD

**Issue by qiancsff** [Xyphyn/photon#384]
On the post editor, there is an redundant symbol.
[发帖的编辑器上，有个多余的符号
![发帖的编辑器上，有个多余的符号](https://github.com/user-attachments/assets/ab79713d-5f90-4a57-80db-34cf5bb06da9)

**Comment by Xyphyn** [comment]
I did not make the Chinese translation, so you can fix it on the weblate:

https://weblate.xylight.dev

**Comment by sevonj** [comment]
> On the post editor, there is an redundant symbol.

The arrow is not pointing at a symbol. It's the handle of the resizable text box. 
See https://developer.mozilla.org/en-US/docs/Web/CSS/resize

It's not very usable on mobile. What if the box resized itself automatically to fit content? I was going to file another bug about resizing: it resets when previewing. Auto-size would take care of that too.

**Comment by qiancsff** [comment]
> I did not make the Chinese translation, so you can fix it on the weblate:
> 
> https://weblate.xylight.dev

Simplified Chinese translation completed
中文简体已翻译完成
![已翻译](https://github.com/user-attachments/assets/99b2f81c-9562-4f80-ba89-8956717c7da1)

**Comment by Xyphyn** [comment]
That symbol is the resize handle, it is up to your browser to handle that. you'll notice it in other places, too, like github:

![image](https://github.com/user-attachments/assets/41b7f173-56a1-4a2f-904f-dc204e9e338c)
