### ISSUE TITLE
Feature request: Auto-expand right sidebar items

### ISSUE THREAD

**Issue by sevonj** [Xyphyn/photon#388]
**Is your feature request related to a problem? Please describe.**
I prefer always seeing the sidebar content. I also don't want to bother clicking through the expandable titles every time.

**Describe the solution you'd like**
- Add a settings toggle to open the sidebar items by default.
- Apply it to CommunityCard in sidebar.
- Apply it to SiteCard in sidebar.

**Describe alternatives you've considered**
- Do it as default, no setting. This may not please everyone.
- Do nothing, leave as is.

**Additional context**
![image](https://github.com/user-attachments/assets/e5093acc-aec4-4540-9a88-33de286c236e)

**Comment by Xyphyn** [comment]
I can make it save what you have expanded.

**Comment by sevonj** [comment]
> I can make it save what you have expanded.

That'd also be great, thanks
