### ISSUE TITLE
How to change the default frontend Lemmy ui to Photon

### ISSUE THREAD

**Issue by qiancsff** [Xyphyn/photon#392]
docker run -p 8080:3000 -e PUBLIC_INSTANCE_URL=example.com ghcr.io/xyphyn/photon:latest

http://example.com:8080/  How to become default http://example.com

**Comment by sevonj** [comment]
This isn't a bug in the code, so maybe it should be a [discussion](https://github.com/Xyphyn/photon/discussions) instead.

Anyway, you need to edit your nginx conf to do the following:
- route web traffic to photon container
- route backend traffic to the lemmy container
- route l.example.com (or whatever subdomain you choose) to the lemmy container

(You are using lemmy-ansible, right?)

**Comment by Xyphyn** [comment]
This is a question, and should be a discussion.
