### ISSUE TITLE
Unsorted/unfiltered content flashing on loading page

### ISSUE THREAD

**Issue by mastazi** [Xyphyn/photon#398]
**Describe the bug**
In the settings, I have set "Default sort" options to 

* Location: Subscribed
* Sort: Active

Whenever I load the home page, for a couple of seconds I see the home page filtered by

* Location: All
* Sort: Active

then if flashes back to the expected contents.

**To Reproduce** (if applicable)
1. Go to options, set "Default sort" to anything other than
    1. Location: All
    1. Sort: Active
1. go back to home page and refresh
1. observe content flashing, for 1-2 seconds you will see content that is not filtered according to your desired settings, then it will revert back to the expected view.

**Expected behavior**
The contents that are visible in home page should be sorted/filtered according to the user's settings.

**Screenshots**
N/A

**Versions**
- Browser: Firefox
- Photon version: 0.19.3-5-g7a0c5adf5

**Comment by Xyphyn** [comment]
Are you using Lemmy on p.lemmy.world? If so, that's because they have SSR enabled and I can't physically fix this without either having users trust me with their credentials, or having some access to the database.

**Comment by mastazi** [comment]
Yes, I am on p.lemmy.world. 
You could use localStorage for things like sorting settings and dark/light theme.

**Comment by Xyphyn** [comment]
localStorage is local, meaning the server cannot access it when it fetches posts initially.

**Comment by mastazi** [comment]
Oh I see, you're right. I'm closing this.
