### ISSUE TITLE
Infinite scrolling

### ISSUE THREAD

**Issue by danielwolbach** [Xyphyn/photon#4]
Rather than having to click "Next" to go to the next page, an automatically reloading infinite scrolling would be a more intuitive solution for a social feed.

PS: This is by far the best Lemmy front end! Thanks for your amazing work!

**Comment by Xyphyn** [comment]
The only issue with this is that Sveltekit's client router doesn't preserve the app state when clicking the back button, meaning you'll lose your scroll position. I'm unsure how I'll fix this without changing the way data is fetched and how the layout works, but I do plan to overhaul the app to be like an SPA soon.
