### ISSUE TITLE
Add Bulgarian translation

### ISSUE THREAD

**Issue by salif** [Xyphyn/photon#402]
**Is your feature request related to a problem? Please describe.**
I added Bulgarian translation on Weblate and already translated 30% of the strings and will continue to translate, I would like to use Photon in Bulgarian language.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Xyphyn** [comment]
Every so often I'll check the weblate and add the new languages. After that it'll automatically update. Will add soon!

**Comment by salif** [comment]
I also have a question about translating posts and comments with Libretranslate. Is it possible to add Bulgarian to the list of languages?

**Comment by salif** [comment]
@Xyphyn  There's an issue on my mobile device when using Bulgarian. The "Link Actions - Media Bias" line is too long, please either make it scrollable or add settings option to remove "Link Actions"

![scr](https://github.com/user-attachments/assets/f9fec16d-f103-4a9e-9f4f-f74d5ab72b61)

**Comment by Xyphyn** [comment]
Fixed in c01968a, and bulgarian was added
