### ISSUE TITLE
When editing a post that had a language selected, it's not shown in the language selection box

### ISSUE THREAD

**Issue by Fxsch** [Xyphyn/photon#416]
**Describe the bug**
When editing a post that had a language selected, it's not shown in the language selection box. When you click on it, it's still shown as selected in the list tho.

**To Reproduce** (if applicable)
1. Create post with a language selected
2. Click the button to edit the post
3. Language selection box is empty
4. Click on it
5. The list still shows the language as selected

**Expected behavior**
The selected language should be shown in the language selection box when editing a post.

**Screen recording**
<video src="https://github.com/user-attachments/assets/daf8e68d-c423-4c49-84ed-6674fccbbbc7"></video>

**Versions**
- Browser: Librewolf 129.0.1-1
- Photon version: 1.31.2

**Comment by Xyphyn** [comment]
I think it's fixed in [190b28a](https://github.com/Xyphyn/photon/commit/190b28a331b95cc8563b423598c2fa5e687a958c)
