### ISSUE TITLE
In Sort drop down menu, when Comments are selected, it shows posts instead

### ISSUE THREAD

**Issue by 4lk** [Xyphyn/photon#420]
**Describe the bug**
In the Frontpage, when I go to the second drop down menu named Sort, if I select Comments or New Replies I see posts instead. No matter which Location is chosen (All, Local, Subscription, Moderator) or which View (Cozy, List, Compact, Legacy)

**To Reproduce** 
1. Go to the Frontpage
2. Click on the Sort drop down menu on the top left
3. Scroll down to Comments or New Replies and select one of them
4. See posts appearing bellow, instead of comments

**Expected behavior**
I would expect to see comments. At least in the Moderator view, to help moderation. 

**Screenshots**
![NoComents](https://github.com/user-attachments/assets/10ab3f9a-3102-4bf3-bd01-a2d86d504d3a)

**Versions**
- Linux Mint 21.3 Cinnamon - Version 6.0.4
- Browser: Firefox 129.0 (64-bit) & Vivaldi 6.9.3447.37 (Stable channel) stable (64-bit) 
- Photon version: 1.31.2

**Comment by 4lk** [comment]
This is not a bug after all. I just realized that when Comments is selected we see posts with most comments and when New Replies is selected we see posts with the newest replies. 

Should I close it?

**Comment by sevonj** [comment]
I translated this line into "most comments". Maybe that would work better in English, too.

**Comment by Xyphyn** [comment]
This isn't necessarily a bug. For clarity's sake, I renamed "Comments" to "Most Comments" in the English translation.

**Comment by sevonj** [comment]
@4lk I think this can be closed now.

https://github.com/Xyphyn/photon/commit/f0134dbbcfa6237ef1ab341b778029646bc295fa
