### ISSUE TITLE
Bug: Settings page mobile overflow?

### ISSUE THREAD

**Issue by sevonj** [Xyphyn/photon#423]
**Describe the bug**
I'm back, and I bring forward yet another css overflow issue. This one is pretty minor, and only seems to affect the settings page. The bottom nav bar goes up and down a bit while scrolling, which tells me that something is too big.

**To Reproduce** (if applicable)
1. Go to settings page in mobile sized screen
2. Scroll

**Expected behavior**
\-

**Screenshots**
[Screencast_20240907_002309.webm](https://github.com/user-attachments/assets/f7ce1c5a-e711-4316-83ac-244c0275adeb)

**Versions**
- Browser: Firefox, Firefox on Android
- Photon version: 1.31.2 / pthn.app

**Comment by Xyphyn** [comment]
I found the culprit, it's the multi select thing. I will fix this soon™️

**Comment by sevonj** [comment]
Yea, was just about to say.
![image](https://github.com/user-attachments/assets/0f791589-cecb-4937-8bc2-fe9d924894e7)

Maybe these controls could be flex-wrapped or otherwise moved below the title and desc on narrow screens.
