### ISSUE TITLE
Translation: Media bias card

### ISSUE THREAD

**Issue by sevonj** [Xyphyn/photon#427]
**Is your feature request related to a problem? Please describe.**
In the media bias card, the values on bias, and factual reporting are not translated. Add them to translation.

**Describe the solution you'd like**
\-

**Describe alternatives you've considered**
\-

**Additional context**
![image](https://github.com/user-attachments/assets/686a28fe-5821-482f-b2f9-ff74b6e9f9dd)

**Comment by Xyphyn** [comment]
These names are taken from the actual dataset, which was a bad idea. I'll localize them

**Comment by Xyphyn** [comment]
Technically closed because I have removed MBFC from Photon
