### ISSUE TITLE
Bug: Long titles cut off when posting

### ISSUE THREAD

**Issue by pbui** [Xyphyn/photon#429]
**Describe the bug**

When creating a post, long titles are cut off with no ability to scroll horizontally.

**To Reproduce** (if applicable)
1. Go to add post.
2. Put in URL with a long title.
3. Generate title.
4. Notice that long titles are cut off and so you cannot read the whole thing.

**Expected behavior**

Long titles should be wrapped so you can view the whole thing.

**Screenshots**

![Screenshot from 2024-09-08 12-18-20](https://github.com/user-attachments/assets/7bda1236-9d41-4b19-9515-3a16804e6e06)

**Versions**
- Browser: Firefox
- Photon version: 1.31.3

**Comment by Xyphyn** [comment]
Oop, this is because I only update the height when you type, I should make it so that it happens whenever the source text changes
