### ISSUE TITLE
Option to disable the MBFC link?

### ISSUE THREAD

**Issue by poVoq** [Xyphyn/photon#436]
https://mediabiasfactcheck.com/ is somewhat controversial and it would be good if there was an option to disable it.

Our co-admin Five made a comprehensive argument against it when the LW bot was spamming it everywhere:

> Who fact-checks the fact-checkers? Fact-checking is an essential tool in fighting the waves of fake news polluting the public discourse. But if that fact-checking is partisan, then it only acerbates the problem of people divided on the basics of a shared reality.
> 
> This is why a consortium of fact-checking institutions have joined together to form the [International Fact-Checking Network](https://www.poynter.org/ifcn/) (IFCN), and laid out a code of principles. You can find a [list of signatories](https://ifcncodeofprinciples.poynter.org/signatories) as well as vetted organizations on their website.
> 
> MBFC is not a signatory to the IFCN code of principles. As a partisan organization, it violates the standards that journalists have recognized as essential to restoring trust in the veracity of the news. 

> Partisan fact-checking sites are worse than no fact-checking at all. Just like how the proliferation of fake news undermines the authority of journalism, the growing popularity of a fact-checking site by a political hack like Dave M. Van Zandt undermines the authority of non-partisan fact-checking institutions in the public consciousness.

**Comment by Xyphyn** [comment]
Sure, I'll add an option.

**Comment by poVoq** [comment]
Thanks!

**Comment by Xyphyn** [comment]
I have nuked it instead as photon shouldn't handle these things itself
