### ISSUE TITLE
Bug: codeblock overflows in feed

### ISSUE THREAD

**Issue by sevonj** [Xyphyn/photon#438]
**Describe the bug**
Codeblocks can overflow in the feed.

I encountered this in search, and community feed.

**To Reproduce** (if applicable)
Offending post: https://lemmy.dbzer0.com/post/21637927

**Expected behavior**
\-

**Screenshots**
![image](https://github.com/user-attachments/assets/ea06ab3d-d94f-42d2-9ac6-ba40651972bf)

**Versions**
- Browser: Firefox
- Photon version: 1.31.3 / phtn.app

**Comment by Xyphyn** [comment]
![image](https://github.com/user-attachments/assets/d1df9848-e1e3-457a-ac4b-e025fca2cd1a)

it works fine for me

**Comment by sevonj** [comment]
?? It's fine for me too now.

I try to always check it's not browser cache or something, but maybe I forgot this time. Also, it happened on phtn.app and not local live preview I had messed with.

Well, since I can't even reproduce this myself, it was probably something on my end, and not photon.
