### ISSUE TITLE
Bug: "Team" link on commuities links to incorrect url path for admins

### ISSUE THREAD

**Issue by lemmyposter212** [Xyphyn/photon#440]
**Describe the bug**
"Team" link on commuities links to incorrect url path for admins
the link should be https://<INSTANCEURL>/c/<COMMUNITY>@<INSTANCE URL>/**settings**/team
but instead is https://<INSTANCEURL>/c/<COMMUNITY>@<INSTANCE URL>/team

**To Reproduce** (if applicable)
1. as an admin Go to community page
2. Click on settings gear
3. click "team"
4. 404 error occurs

**Expected behavior**
the community's mod team is shown

**Screenshots**
![image](https://github.com/user-attachments/assets/3470cb90-11d0-4362-9f10-101667706e0a)

**Versions**
- Browser: Firefox
- Photon version: v1.31.2-fix.1

**Comment by sevonj** [comment]
Looks like this was fixed a month ago: 304b35be6cfc1f4657b2eabb7cddeaf762be20a3

You're one photon release behind, and the current one has the fix.

**Comment by Xyphyn** [comment]
You're on an old version of photon.

**Comment by lemmyposter212** [comment]
great, thanks!
