### ISSUE TITLE
Should the navbar avatar URL use a query string?

### ISSUE THREAD

**Issue by tfaughnan** [Xyphyn/photon#45]
While writing my contribution in #44 I noticed that the Avatar component (for posts, comments, etc.) appends the query string `?format=webp&thumbnail={width * 2}` to the avatar URL, which requests a WebP format and a smaller size. The navbar avatar does not do this. My personal avatar happens to be quite large (1024x1388), much larger than the navbar avatar needs. Should we append a query string here too?

Example URLs:

- with: https://lemmy.ndlug.org/pictrs/image/caf31a85-e75d-49ac-a70c-710eeb1be62e.jpeg?format=webp&thumbnail=128
- without: https://lemmy.ndlug.org/pictrs/image/caf31a85-e75d-49ac-a70c-710eeb1be62e.jpeg

**Comment by Xyphyn** [comment]
Yes, a thumbnail of 64 should do (I think the actual profile is 48px in size)
