### ISSUE TITLE
Brackets in title wrongly treated as tag

### ISSUE THREAD

**Issue by KaKi87** [Xyphyn/photon#463]
**Describe the bug**
Brackets in the middle of a title are wrongly treated as containing a tag.

**To Reproduce** (if applicable)
1. Visit [a post which title contains brackets in the middle of it](https://phtn.app/post/jlai.lu/11613098) ;
2. Notice brackets not visible in the title ;
3. Notice brackets contents treated as tag.

**Expected behavior**
The brackets wouldn't be treated as containing a tag.
Brackets would only be treated as tag if positioned at the beninning of a title, e.g. :

- `[Foo] Lorem ipsum` -> label `Foo` + title `Lorem ipsum` ;
- `[Foo] [Bar] Lorem ipsum` -> labels `Foo` & `Bar` + title `Lorem ipsum` ;
- `Lorem ipsum [...] adipiscing elit` -> only title `Lorem ipsum [...] adipiscing elit` ;
- `[Foo] Lorem ipsum [...] adipiscing elit` -> label `Foo` + title `Lorem ipsum [...] adipiscing elit`
- `[Foo] [Bar] Lorem ipsum [...] adipiscing elit` -> labels `Foo` & `Bar` + title `Lorem ipsum [...] adipiscing elit`

**Screenshots**

| Lemmy |
| :--- |
| ![](https://github.com/user-attachments/assets/9661d84f-6c73-42d3-898c-9fb925678b48) |
| **Photon** |
| ![](https://github.com/user-attachments/assets/bebb5eb2-4cd6-45ce-91a8-a138e7cdc90d) |

**Versions**
- Browser: Vivaldi 6.9.3447.54
- Photon version: 1.31.5

---
Thanks

**Comment by Xyphyn** [comment]
Fixed in 8958321031d334d73ec9efccec9d354999adad98
