### ISSUE TITLE
Settings: Add Interface Language

### ISSUE THREAD

**Issue by kristofzerbe** [Xyphyn/photon#465]
Of all the Lemmy UIs, I like Photon the most ... but it doesn't give me a choice of interface language. Where I can set my desired language in the settings of the standard UI, this is missing in Photon and the browser language is used.

I only have “German” browsers, but for some sites I prefer the UI in the original English language. It would therefore be desirable if users could set this instead of assuming something.

**Comment by Xyphyn** [comment]
That's already there?

Settings > Language (at the top)

![Screenshot_20241025-061015.png](https://github.com/user-attachments/assets/9c060516-f0f1-4903-b144-5ee02a330e59)

**Comment by Xyphyn** [comment]
No worries
