### ISSUE TITLE
Photon gives 500 error for logged in users after upgrading to Lemmy 0.19.6

### ISSUE THREAD

**Issue by poVoq** [Xyphyn/photon#472]
**Describe the bug**
After upgrading our Lemmy instance to 0.19.6 the instance locked Photon frontend has become inaccessible for users logged into it. Guest visitors can still use it. 

**To Reproduce** (if applicable)
1. Log into Photon
2. Upgrade Lemmy to 0.19.6
3. Try to access Photon
4. See 500 error, that makes it impossible to even log out.

**Versions**
- Browser: Firefox
- Photon version: latest official container 1.31.4

**Comment by Xyphyn** [comment]
I tried this on lemmy.zip which is also on 0.19.6 and couldn't reproduce.

Can I make an account on slrpnk.net to try and diagnose the issue?

**Comment by Xyphyn** [comment]
Looking at the console log there seems to be an issue with CORS headers, which would explain why there isn't a problem on lemmy.zip.

**Comment by poVoq** [comment]
Hmm, I newly added the `cors_origin: "*"` part to the config.hjson of Lemmy, otherwise I didn't change anything on the reverse-proxy or so compared to the previous version.

**Comment by Xyphyn** [comment]
Does alexandrite work?

**Comment by poVoq** [comment]
Alexandrite seems to not allow logging in, so maybe it is a more general issue? Lemmy-ui seems to work fine though.

Maybe they changed something in the recommended reverse-proxy setup as well?

**Comment by Xyphyn** [comment]
Lemmy UI would work because it's running on the same domain as the API, so cors doesn't apply. Clients on separate domains would have to use CORS. What about Voyager?

**Comment by poVoq** [comment]
Same with Voyager. So I guess there is something on my side I need to investigate.

**Comment by poVoq** [comment]
Odd, removing that new `cors_origin: "*"` from the config.hjson seems to have fixed it. Very odd though.

**Comment by poVoq** [comment]
Made a upstream bug report: https://github.com/LemmyNet/lemmy/issues/5185
