### ISSUE TITLE
Mod queue reporter incorrectly also shows as author of reported content

### ISSUE THREAD

**Issue by CorvetteCole** [Xyphyn/photon#48]
In the below screenshot, CatBusBand did the report, but did not author the post.

![Screenshot_20230731-073656](https://github.com/Xyphyn/photon/assets/19213965/4a15b535-60bb-444f-8ef8-e0a5c1b215bf)

**Comment by SigurdVie** [comment]
I also have met this issue.

What shows in report log:
![image](https://github.com/Xyphyn/photon/assets/49611200/5f2a22a4-4c04-4243-ba03-a3a6c9004645)

The actual comment:
![image](https://github.com/Xyphyn/photon/assets/49611200/483886d5-622a-4719-9b30-f613563d5017)

**Comment by Xyphyn** [comment]
I see, I know what the issue is. Fixing
