### ISSUE TITLE
Spoiler tags don't work in post preview

### ISSUE THREAD

**Issue by LinuxSBC** [Xyphyn/photon#49]
For example, at least right now, the [second post](https://photon.xylight.dev/post/lemm.ee/2080470) in https://photon.xylight.dev/c/liftoff@lemmy.world?sort=TopWeek has a spoiler in the description. In the feed, the spoiler is visible, while it is hidden in the post.

**Comment by Xyphyn** [comment]
Fixed in v0.4.15
