### ISSUE TITLE
Shown option to delete a post when the author is from my instance, despite not being the author myself

### ISSUE THREAD

**Issue by CorvetteCole** [Xyphyn/photon#52]
See below screenshots. I don't know if this is just because I am an admin or if this happens normally, I will test it with a normal account when I have time today. If this is simply because I am an admin, feel free to close this issue. Additionally, I figure I should tell you that I'll be deploying a custom tool soon to auto-update lemdro.id when you release new versions :) 

Thanks again for your work!

![Screenshot_20230731-182041](https://github.com/Xyphyn/photon/assets/19213965/a62fb3b7-81eb-4a38-8e5f-8379a16bde67)
![Screenshot_20230731-182045](https://github.com/Xyphyn/photon/assets/19213965/9e9e4271-3b6d-4afc-80fd-1e0fcb1e82e0)

**Comment by Xyphyn** [comment]
I think this was an artifact of my isMutable function, I originally was gonna make it so mods/admins can delete through this but I moved it to a separate menu.

**Comment by Xyphyn** [comment]
Also, what version were those screenshots taken on? The navbar seems to be clipping out of the screen.

**Comment by CorvetteCole** [comment]
I'm pretty sure these screenshots were taken on a pre-0.4.10 version, but https://p.lemdro.id has since updated and I cannot reproduce it any longer. Digging the better desktop screen usage btw
