### ISSUE TITLE
Instance icon is cropped too small

### ISSUE THREAD

**Issue by CorvetteCole** [Xyphyn/photon#53]
LOVE the work done to show the instance icon in the top left. Only problem is it crops it into a relatively tight circle. This leaves the lemdro.id icon looking in a rather sorry state: 
![image](https://github.com/Xyphyn/photon/assets/19213965/c99c3397-a09a-4021-8dcc-b7c8ba7fd12e)

Compared to how it should look:
![image](https://github.com/Xyphyn/photon/assets/19213965/9b2af217-d694-4ca5-baa0-6487feac2110)

Maybe just adjust how much cropping the circle does? You can see the bottom screenshot here still does have a circle but it is much "larger". Some other frontends don't even force the circle. It is kind of up to you design-wise. Thanks again!

**Comment by Xyphyn** [comment]
Would cropping it as a square instead be fine?
