### ISSUE TITLE
[Feature request] Mark posts as read on scroll

### ISSUE THREAD

**Issue by pitrisss** [Xyphyn/photon#54]
Is it possible to implement this feature?
Thank you

**Comment by Xyphyn** [comment]
This is kinda horrible for rate limiting but possible. If you hover over a post title it automatically marks as read

**Comment by CorvetteCole** [comment]
yeah I'm against this change as an admin lol

**Comment by Xyphyn** [comment]
Maybe I can do it client side, but for now it's bad for network reasons.

**Comment by hanubeki** [comment]
@Xyphyn
> If you hover over a post title it automatically marks as read

I don't really like this behaviour, I'm tired of using it because of this.

**Comment by Xyphyn** [comment]
> @Xyphyn
> > If you hover over a post title it automatically marks as read
> 
> I don't really like this behaviour, I'm tired of using it because of this.

This is because it prefetches the post. I can add an option to not mark posts as read or to disable prefetching.

**Comment by hanubeki** [comment]
Okay, let's move to #157
