### ISSUE TITLE
[Feature Request] Show Post instance

### ISSUE THREAD

**Issue by AndroidKitKat** [Xyphyn/photon#57]
Similar to the show a user's instance toggle, I think it would be handy to have the post's instance shown as well. 

This is where I mean (sorry for the useless arrow). 
![image](https://github.com/Xyphyn/photon/assets/39808659/7cc6dfdc-3081-4984-b191-6383c10d0658)

V/r,

Mike

**Comment by Xyphyn** [comment]
Do you mean the community it was posted to? Sure.

**Comment by Xyphyn** [comment]
Added in v0.4.30
