### ISSUE TITLE
Feature request: Allow for resizable sidebars

### ISSUE THREAD

**Issue by mbestavros** [Xyphyn/photon#61]
Using v0.4.22.

As is, the two sidebars (community listing on the left, and community info on the right) both appear to be static widths. I personally find the communities sidebar on the left to be too wide, pushing the main content off to the right side too much.

I'd easily be able to fix this myself if I could adjust the widths of each sidebar with a little slider, much like Slack or VS Code (to give two examples).

**Comment by Xyphyn** [comment]
ugh i hate when production results differ from dev results

**Comment by Xyphyn** [comment]
Almost successfully added this but for some reason in production it stops working but it works on my dev server

**Comment by Xyphyn** [comment]
Added

**Comment by Xyphyn** [comment]
![image](https://github.com/Xyphyn/photon/assets/80978739/bf0ba898-08b7-4247-b070-d2ecd6acd0cd)

Use this little thing to resize, with CSS there isn't a way to place it somewhere else

**Comment by pbui** [comment]
Might need a minimum width... when you collapse after resizing, you get this:

![Screenshot from 2023-08-02 16-31-21](https://github.com/Xyphyn/photon/assets/3976244/c6ce75a9-b5ff-4871-8351-957bdd4d1f9f)

**Comment by Xyphyn** [comment]
doesn't happen on the dev server, sigh

I hate when tailwind does this lol

**Comment by Xyphyn** [comment]
fixed

**Comment by jgeorgeson** [comment]
Did this feature get removed? Or is there a setting for instance admins to disable it? I'm using https://photon.lemmy.world and I'm unable to collapse or resize the side panel anymore. I don't see a way to find the Photon version they have deployed there.

**Comment by jgeorgeson** [comment]
Bummer. I have an 11" Surface Pro 3 that I rarely use a mouse with. The sidebars are wide enough that I can't comfortably reach the scrollable center pane with my thumb when my hand is on the side of the device in landscape orientation. Can you maybe add a user setting for it?

**Comment by Xyphyn** [comment]
Just so I know which screen size you're using, do you see a sidebar in the right?

**Comment by jgeorgeson** [comment]
yes. My primary attention here would be on collapsing the the sidebar on the right, but I can see left-handed users wanting to collapse the sidebar on the right to scroll with their thumb, too.

![image](https://github.com/Xyphyn/photon/assets/10238523/3cd4a900-2f2c-4d93-98d2-278ebe46d1ab)
