### ISSUE TITLE
Unread indicator no longer works

### ISSUE THREAD

**Issue by pbui** [Xyphyn/photon#62]
With 2da415b we no longer call `setInterval` to periodically update the number of unreads and reports the user has.  Because of this, we no longer get a notification dot on the avatar icon or the inbox in the dropdown menu.

I've tried to restore this functionality with the following code in `src/lib/lemmy.ts`:

```
setInterval(async () => {
  const auth = get(profile)

  if (!auth?.jwt || !auth?.user) return

  const response = await getClient().getUnreadCount({
    auth: auth.jwt
  })

  auth.user.unreads =
    response.mentions +
    response.private_messages +
    response.replies

  if (amModOfAny(auth.user)) {
    const reports = await getClient().getReportCount({
      auth: auth.jwt
    })

    auth.user.reports =
      reports.comment_reports +
      reports.post_reports +
      (reports.private_message_reports ?? 0)
  }
}, 30 * 1000)
```

This appears to work for restoring the red notification dot to the **inbox** in the dropdown menu, but not for the avatar itself.

I can make a PR with this initial attempt, but I'm not sure how to get the notification dot to show up the avatar... looking at the DOM via the web inspection tools, it seems to never actually add the corresponding `div` for the avatar, but does so for the inbox menu.

**Comment by Xyphyn** [comment]
Will fix today

**Comment by Xyphyn** [comment]
This is because of how stores work. in .svelte files, the compiler automatically converts the stores to be reactive, but in TS files, `get` isn't reactive. so you have to use `store.update()`

**Comment by Xyphyn** [comment]
Like this

```ts
setInterval(async () => {
  if (!get(profile)) return

  const { user, jwt } = get(profile)!
  if (!jwt || !user) return

  const response = await getClient().getUnreadCount({
    auth: jwt,
  })

  user.unreads =
    response.mentions + response.private_messages + response.replies

  if (amModOfAny(user)) {
    const reports = await getClient().getReportCount({
      auth: jwt,
    })

    user.reports =
      reports.comment_reports +
      reports.post_reports +
      (reports.private_message_reports ?? 0)
  }

  profile.update((p) => ({
    ...p!,
    user: user,
  }))
}, 30 * 1000)
```

**Comment by pbui** [comment]
Ah, OK.  I tried doing `update()` on `user` but got runtime errors... didn't think of updating the `user` inside of the `profile`.
