### ISSUE TITLE
ARM docker images

### ISSUE THREAD

**Issue by AvatarMomo** [Xyphyn/photon#66]
It would be great if ARM based images are available.
if it helps, this is the workflow for mlmym for crossplatform builds
https://github.com/rystaf/mlmym/blob/main/.github/workflows/docker.yml

**Comment by Xyphyn** [comment]
For some reason I can't test locally

**Comment by ismailkarsli** [comment]
I need this too. Svelte is a web app so it should be easy right?

**Comment by Xyphyn** [comment]
I don't know how to do this and none of the guides i tried worked so someone could make a PR if they want this

**Comment by Xyphyn** [comment]
You can see my failed attempts on 

https://github.com/Xyphyn/photon/actions

I cannot figure out how to get this shit working

**Comment by Xyphyn** [comment]
It stopped attempting in general and won't even show an error now

**Comment by ismailkarsli** [comment]
I forked the repo and re-run the action and it seems worked.
https://github.com/ismailkarsli/photon/actions/runs/5919519203/job/16049870007
https://github.com/ismailkarsli/photon/pkgs/container/photon

**Comment by Xyphyn** [comment]
The code i pushed 7 minutes ago ended up working. Arm64 images are now available

**Comment by AvatarMomo** [comment]
Thanks @Xyphyn  @ismailkarsli
