### ISSUE TITLE
Opening lemmy.world returns error 500

### ISSUE THREAD

**Issue by damp-canary** [Xyphyn/photon#75]
Hi,

Opening photon.lemmy.wotld in Chrome on Android fails with error 500 and message:

Failed to fetch dynamically imported module: https://photon.lemmy.world/_app/immutable/nodes/12.73a723de.js

With regards,
Canary

**Comment by Xyphyn** [comment]
This is because lemmy.world's servers, including the one photon.lemmy.world was hosted on, went down for a few minutes. Should be fine now.
