### ISSUE TITLE
Possible scroll weird behavior

### ISSUE THREAD

**Issue by MoraMartin99** [Xyphyn/photon#77]
**OS: Android 12**
**Browser: Firefox 116 and Brave 1.56.20**
**Reproducible steps**

1. Click on about button
2. scroll down in the menu

**Expected behavior**

The scroll only has effect on the menu, not in the behind timeline

https://github.com/Xyphyn/photon/assets/95828792/79365974-cd1b-4151-9dea-95e3fb132025

**Comment by Xyphyn** [comment]
Weird.

FYI: dark reader is making the colors of the site weird

**Comment by Xyphyn** [comment]
After scrolling for 6 hours through the tailwind docs to pass the time I found out how to fix this

`overscroll-contain`
