### ISSUE TITLE
Keyboard shortcuts in editor

### ISSUE THREAD

**Issue by dacwatson** [Xyphyn/photon#78]
Accessing photon through flatpak firefox on wayland. 

Text editor hotkeys get sent to FF rather than the site-- for example, `crtl + i` should italicize, `crtl + k` should insert link markdown.

**Comment by Xyphyn** [comment]
Good idea, will add soon

**Comment by Xyphyn** [comment]
Added shortcuts for bold, italics, strikethrough, and headers.
