### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [Xyphyn/photon#8]
I see you have no LICENSE file for this project. The default is copyright.

I would suggest releasing the code under the AGPL-3.0-or-later license (like Lemmy) so that others are encouraged to contribute changes back to your project.

**Comment by Xyphyn** [comment]
Done

**Comment by TechnologyClassroom** [comment]
Did you mean to set it to GPLv3 and not **A**GPLv3? Lemmy uses AGPLv3.

**Comment by Xyphyn** [comment]
Whoops, fixing.
