### ISSUE TITLE
Post creation text editor field possible improvements

### ISSUE THREAD

**Issue by dacwatson** [Xyphyn/photon#80]
The size of the post editing field seems fine for a few sentences, but when typing a longer post, it quickly becomes insufficient. Additionally, the resizing handle is quite low contrast and some users might not be able to see it. 

Possible solutions:
- Increase default size of text editor field
- Have size of text editor field expand as the user types up to a maximum size

**Default size:**
![image](https://github.com/Xyphyn/photon/assets/70728355/ea1a4ce8-815c-492d-9fd7-7f9f6679e80a)
**What seems like a more comfortable size for a larger post:**
![image](https://github.com/Xyphyn/photon/assets/70728355/77ebc402-a353-4957-9b62-29d321fd2ab3)

**Comment by Xyphyn** [comment]
Expanded in [adfe8a6](https://github.com/Xyphyn/photon/commit/adfe8a6e7dad205f9dcc8fcaa0a1ee1bb3c79373)
