### ISSUE TITLE
Issue uploading image

### ISSUE THREAD

**Issue by dacwatson** [Xyphyn/photon#81]
Attempting to upload a png returns an error:
` SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

Screenshot:
![Screenshot from 2023-08-08 23-05-44](https://github.com/Xyphyn/photon/assets/70728355/c5e3e887-be61-4815-9a33-669cd4063ced)

The png I tried to upload:
![outer_wall](https://github.com/Xyphyn/photon/assets/70728355/8448e619-c210-46a5-9803-d2128d813800)

p.s.-- sorry for spamming the issues. Wanted to say I love the feel of this client and it's my favorite one so far :)

**Comment by Xyphyn** [comment]
No such thing as spamming issues if they're unique! Thanks for reporting this.

I think that the file might be over the size limit or something. I'll add more user friendly errors later.

**Comment by Xyphyn** [comment]
This seems like an issue of the instance itself. What instance are you on?
