### ISSUE TITLE
Put dropdown menu action buttons on the card in card view if they can fit.

### ISSUE THREAD

**Issue by YousufSSyed** [Xyphyn/photon#84]
This is what photon looks like on my computer. There are a bunch of options hidden in a hamburger menu which is very inefficient compared to other Lemmy UIs and new Reddit. What Photon could do, is put the action buttons on the card next to the comments button if they can fit. If its wide enough for only one button and not the other two on a certain width, then show the one.

**Comment by Xyphyn** [comment]
Might be complicated to add, but good idea.

**Comment by YousufSSyed** [comment]
Or what you could is show all the buttons, and if the width is too low then just show the icons.
