### ISSUE TITLE
Single-instance mode

### ISSUE THREAD

**Issue by KAMiKAZOW** [Xyphyn/photon#87]
If instance admins decide they want to only to use Photon instead of Lemmy-UI, an easy way to configure Photon to support sign-ups and not have users confuse with instance selection at login would be beneficial. (Perhaps Photon could access features not available through the regular API as well?)

**Comment by Xyphyn** [comment]
You can currently restrict Photon to a single instance with the `PUBLIC_INSTANCE_URL` environment variable, like `PUBLIC_INSTANCE_URL=lemmy.world`. You can see what the result looks like on https://photon.lemmy.world.

I'll implement signups though, sure.

**Comment by KAMiKAZOW** [comment]
I know how the result looks like on Lemmy World. It still has the instance selection, the actual selection is just greyed out. Makes no sense to have to click Log in twice just to log in.

**Comment by Xyphyn** [comment]
Ah, I see.

Well, if you have no accounts, you no longer have to click login twice from the menu.

**Comment by KAMiKAZOW** [comment]
> I'll implement signups

> Xyphyn closed this as completed

In which commit was this completed? Can't see it.

**Comment by Xyphyn** [comment]
I fixed the login twice, not added signups, don't know why i closed this

**Comment by Xyphyn** [comment]
Signups were added a while ago. Closing.
