### ISSUE TITLE
Add "read" button for individual messages in inbox

### ISSUE THREAD

**Issue by dacwatson** [Xyphyn/photon#88]
**Is your feature request related to a problem? Please describe.**
Sometimes when I'm going through my inbox, I have several messages that I reply to one at a time. It seems like posts aren't being marked as read after I view them, so it would be nice to have a manual "mark as read" button on each inbox entry.

**Comment by Xyphyn** [comment]
Good idea. Will add soon

**Comment by Xyphyn** [comment]
Added
