### ISSUE TITLE
Sorting by Read Doesn't Pull Posts from New Pages

### ISSUE THREAD

**Issue by Xusontha** [Xyphyn/photon#90]
**Describe the bug**
When you sort by read, it seems Photon just pulls a page then hides the posts already seen. This means if you've seen all the posts on the first page but none on the second, when you reload the first page it will show nothing until you go to the second page.

**To Reproduce** (if applicable)
1. Go to Settings and turn on "Hide read posts"
2. Go back to the main page and make sure all the posts on a page are marked as read
3. Reload

**Expected behavior**

**Screenshots**
First page after all posts have been read and then reloaded
![image](https://github.com/Xyphyn/photon/assets/128322432/07884649-f675-4931-b33b-a0e64fdcca5d)
Second page after first blank page
![image](https://github.com/Xyphyn/photon/assets/128322432/41b58608-ce58-44de-bddc-ae61ed986f4b)

**Versions**
- Browser: Firefox
- Photon version: 0.5.5

**Comment by Xyphyn** [comment]
This is why I hesitated to add this. There's no server side option to hide unread posts :/

**Comment by Xusontha** [comment]
Huh, that's tricky. I'm not super good with development, but maybe something could be done where it checks how many posts will be shown, then if it's below a threshold it goes to the next page and adds those to the first or something like that?

**Comment by Xyphyn** [comment]
It's possible. Would be pretty difficult though

**Comment by Xusontha** [comment]
I'm not super knowledgeable about coding, so it's probably just be a bad idea. I can just go to the next page lol

**Comment by Xyphyn** [comment]
Found a way to use it using lemmy's own settings. It has been moved to Main Menu > Profile > Settings > Show read posts
