### ISSUE TITLE
Admins do not have access to moderation actions

### ISSUE THREAD

**Issue by pbui** [Xyphyn/photon#92]
**Describe the bug**
As an instance administrator, I get moderation reports.  However, when I click on the reported posts, I do not have the moderation actions such as to remove the post or ban the user.

**To Reproduce** (if applicable)
1. As an admin, go to the reports page.
2. Click on any reported post.
3. Notice that you do not have any moderation actions present.

**Expected behavior**
Using the normal Lemmy-UI, I can remove posts or ban a user as an instance administrator.

**Versions**
- Browser: Firefox
- Photon version: 0.6.1

**Comment by Xyphyn** [comment]
Is this only on the reports page? Can you access mod actions when you click the post itself?

**Comment by Xyphyn** [comment]
Unfortunately I can't fix this until I'm back at my desktop

**Comment by pbui** [comment]
No worries, take your time.

I do not see the mod actions on the reports page nor do I see them on the post itself.

Reports page:

![Screenshot from 2023-08-10 10-45-32](https://github.com/Xyphyn/photon/assets/3976244/f9137283-c5f2-4fdb-afdf-cec9acb6c2d4)

Post itself:

![Screenshot from 2023-08-10 10-45-59](https://github.com/Xyphyn/photon/assets/3976244/7cd09843-86ca-4ffa-ac52-d6c03d053331)

This was already removed, but you can see there are no Mod Actions.

**Comment by Xyphyn** [comment]
should be fixed now
