### ISSUE TITLE
Make `CTRL` + `Enter` work to send post/comment

### ISSUE THREAD

**Issue by Hans5958** [Xyphyn/photon#94]
**Is your feature request related to a problem? Please describe.**
Usually, pressing <kbd>CTRL</kbd> + <kbd>Enter</kbd> on internet forms would equal to submitting the form (or, pressing the Submit button). This includes, but not limited to:
- Creating an issue/PR/discussion or commenting to an issue/PR/discussion/commit on GitHub
- Creating a post or sending a comment on Reddit or Lemmy (select clients)
- Sending a comment on YouTube
I expect this would be the same on Photon, but to my surprise, doing <kbd>CTRL</kbd> + <kbd>Enter</kbd> does nothing when creating a post or sending a comment.

**Describe the solution you'd like**
I want <kbd>CTRL</kbd> + <kbd>Enter</kbd> to work when creating a post or sending a comment. 

**Describe alternatives you've considered**
None, other than manually pressing the "Submit" button.

**Additional context**
None

**Comment by Xyphyn** [comment]
Good idea, will add soon.
