### ISSUE TITLE
Add an option to show the community about section to the right of the feed.

### ISSUE THREAD

**Issue by YousufSSyed** [Xyphyn/photon#95]
**Is your feature request related to a problem? Please describe.**
I have to go to the community page and click "about" to see the community info whereas on Reddit and other Lemmy frontends I don't since they show the info on the right side.

**Describe the solution you'd like**
Show the community info on the right side by default and a << button on the top right corner which can toggle it.

**Comment by Xyphyn** [comment]
How wide is your screen? On 16:9 screens it is shown on the right.

**Comment by YousufSSyed** [comment]
I have a 16'' MBP and this is what it looks like in Firefox with the left sidebar shown. I think there should be a setting to force it on. Reddit shows the right sidebar on that width.
<img width="1107" alt="Screenshot 2023-08-12 at 8 30 01 PM" src="https://github.com/Xyphyn/photon/assets/42646062/f8911da8-ad2c-4cc0-894b-df830e737fe3">
<img width="1147" alt="Screenshot 2023-08-14 at 12 00 19 PM" src="https://github.com/Xyphyn/photon/assets/42646062/55f981fb-34e4-4cd8-8983-27198b3e640f">

**Comment by Xyphyn** [comment]
Alright, will add

**Comment by BuildBackBuehler** [comment]
Seems you implemented it, but it doesn't appear that it is collapsible(?). 

I'll try to tweak it, lest that's easy for you. I have a limited knowledge of Next, I see this is in Svelte, haven't looked into its syntax so ¯\_(ツ)_/¯, but if its similar enough, np.
