### ISSUE TITLE
Embedding Image in Reply Doesn't Scale Size

### ISSUE THREAD

**Issue by Xusontha** [Xyphyn/photon#97]
**Describe the bug**
When you go to embed an image in a comment and then preview the reply, the size of the box doesn't scale

**To Reproduce** (if applicable)
1. Go to post and fill out a reply to someone with ! [alttext] (url)"
2. Click on Preview

**Expected behavior**
The reply box to scale to the size of the image

**Screenshots**
![image](https://github.com/Xyphyn/photon/assets/128322432/c939c74a-ebb3-4723-bad2-c5196cb9b705)
![image](https://github.com/Xyphyn/photon/assets/128322432/e7fbf602-9e97-4a20-9c76-7075591d8713)
(scaled down width of browser window to not make really wide screenshot)

**Versions**
- Browser: Firefox
- Photon version: 0.7.6

**Comment by Xyphyn** [comment]
I guess I could use a min-height but I've extended the height of the comment form
