### ISSUE TITLE
Switching Between Profiles on Profile Page Breaks Profile

### ISSUE THREAD

**Issue by Xusontha** [Xyphyn/photon#98]
**Describe the bug**
When you switch accounts while viewing the profile page, the profile page only shows      {}
  
**To Reproduce** (if applicable)
1. Login to two accounts and while logged into one go to their profile
2. Click on the other account on the sidebar (or you can use the account switcher then just click the back button, either works)
4. See error and error doesn't go away until you navigate to another menu and back

https://github.com/Xyphyn/photon/assets/128322432/1e07984d-0d26-4dcb-8ded-d69e12bbf91a

**Versions**
- Browser: Chromium
- Photon version: 0.7.7
  - check in the bottom of the main menu.

**Comment by Xyphyn** [comment]
i hate how route invalidation works in sveltekit

will fix later

**Comment by mbednarek360** [comment]
Seems to also happen while refreshing the page for a single account. Only the user tab of the profile page seems to be affected.

**Comment by Xyphyn** [comment]
Fixed in v0.9.22
